/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bookstore.ui;

import com.bookstore.ui.inventory_menu.ChangePassword;
import com.bookstore.ui.inventory_menu.DaftarPO;
import com.bookstore.ui.inventory_menu.CreatePurchaseOrder;
import com.bookstore.ui.inventory_menu.RackConfig;
import com.bookstore.ui.inventory_menu.ReceivedPurchaseOrder;
import com.bookstore.ui.inventory_menu.StockBook;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author rifki
 */
public class InventoryDashboardFrame extends javax.swing.JFrame {
    /**
     * Creates new form InventoryDashboardFrame
     */
    public InventoryDashboardFrame() {
       
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Toko Buku - Admin Gudang");
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int option = JOptionPane.showConfirmDialog(
                        InventoryDashboardFrame.this,
                        "Apakah Kamu Yakin Ingin Keluar Dari Aplikasi?",
                        "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
                if(option == JOptionPane.YES_OPTION){
                    InventoryDashboardFrame.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    InventoryDashboardFrame.this.setVisible(false);
                    LoginFrame loginFrame = new LoginFrame();
                    loginFrame.setVisible(true);
                    loginFrame.requestFocus();
                } else {
                    InventoryDashboardFrame.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ChangePassword = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        DaftarStockBuku = new javax.swing.JMenuItem();
        RackConfig = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        CreatePOMenu = new javax.swing.JMenuItem();
        CheckPOMenu = new javax.swing.JMenuItem();
        receivedPOMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\User\\Documents\\kuliah\\semester4\\pemrograman_desktop\\project\\toko_buku\\Fix_Tubes\\assets\\images\\dashboard-inventory-img-scale.jpg")); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(84, 119, 146));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("File");

        ChangePassword.setBackground(new java.awt.Color(84, 119, 146));
        ChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        ChangePassword.setText("Ganti Password");
        ChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordActionPerformed(evt);
            }
        });
        jMenu1.add(ChangePassword);

        Exit.setBackground(new java.awt.Color(84, 119, 146));
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("Keluar");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Inventory");

        DaftarStockBuku.setBackground(new java.awt.Color(84, 119, 146));
        DaftarStockBuku.setForeground(new java.awt.Color(255, 255, 255));
        DaftarStockBuku.setText("Daftar Stock Buku");
        DaftarStockBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarStockBukuActionPerformed(evt);
            }
        });
        jMenu2.add(DaftarStockBuku);

        RackConfig.setBackground(new java.awt.Color(84, 119, 146));
        RackConfig.setForeground(new java.awt.Color(255, 255, 255));
        RackConfig.setText("Pengaturan Rak");
        RackConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RackConfigActionPerformed(evt);
            }
        });
        jMenu2.add(RackConfig);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Purchase Order");

        CreatePOMenu.setBackground(new java.awt.Color(84, 119, 146));
        CreatePOMenu.setForeground(new java.awt.Color(255, 255, 255));
        CreatePOMenu.setText("Buat PO");
        CreatePOMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePOMenuActionPerformed(evt);
            }
        });
        jMenu3.add(CreatePOMenu);

        CheckPOMenu.setBackground(new java.awt.Color(84, 119, 146));
        CheckPOMenu.setForeground(new java.awt.Color(255, 255, 255));
        CheckPOMenu.setText("Daftar PO");
        CheckPOMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPOMenuActionPerformed(evt);
            }
        });
        jMenu3.add(CheckPOMenu);

        receivedPOMenu.setBackground(new java.awt.Color(84, 119, 146));
        receivedPOMenu.setForeground(new java.awt.Color(255, 255, 255));
        receivedPOMenu.setText("Terima PO");
        receivedPOMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receivedPOMenuActionPerformed(evt);
            }
        });
        jMenu3.add(receivedPOMenu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DaftarStockBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarStockBukuActionPerformed
        StockBook stockBook = new StockBook(this);
        stockBook.setVisible(true);
        stockBook.requestFocus();
        this.setEnabled(false);
    }//GEN-LAST:event_DaftarStockBukuActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Apakah Kamu Yakin Ingin Keluar Dari Akun?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.setVisible(false);
            LoginFrame loginFrame = new LoginFrame();
            loginFrame.setVisible(true);
            loginFrame.requestFocus();
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void ChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordActionPerformed
        ChangePassword changePassword = new ChangePassword();
        changePassword.setVisible(true);
    }//GEN-LAST:event_ChangePasswordActionPerformed

    private void RackConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RackConfigActionPerformed
        RackConfig rakConfig = new RackConfig(this);
        rakConfig.setVisible(true);
        rakConfig.requestFocus();
        this.setEnabled(false);
    }//GEN-LAST:event_RackConfigActionPerformed

    private void CreatePOMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePOMenuActionPerformed
        CreatePurchaseOrder poManagement = new CreatePurchaseOrder(this);
        poManagement.setVisible(true);
        poManagement.requestFocus();
        this.setEnabled(false);
    }//GEN-LAST:event_CreatePOMenuActionPerformed

    private void CheckPOMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPOMenuActionPerformed
        DaftarPO daftarPO = new DaftarPO(this);
        daftarPO.setVisible(true);
        daftarPO.requestFocus();
        this.setEnabled(false);
    }//GEN-LAST:event_CheckPOMenuActionPerformed

    private void receivedPOMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivedPOMenuActionPerformed
        ReceivedPurchaseOrder receivedPurchaseOrder = new ReceivedPurchaseOrder(this);
        receivedPurchaseOrder.setVisible(true);
        receivedPurchaseOrder.requestFocus();
        this.setEnabled(false);
    }//GEN-LAST:event_receivedPOMenuActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ChangePassword;
    private javax.swing.JMenuItem CheckPOMenu;
    private javax.swing.JMenuItem CreatePOMenu;
    private javax.swing.JMenuItem DaftarStockBuku;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem RackConfig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem receivedPOMenu;
    // End of variables declaration//GEN-END:variables
}
