/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bookstore.ui;

import com.bookstore.ui.inventory_menu.ChangePassword;
import com.bookstore.ui.administrator_menu.MaintenancePegawai;
import com.bookstore.ui.administrator_menu.MaintenanceRolePegawai;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author rifki
 */
public class SuperAdminDashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManagerDashboardPanel
     */
    public SuperAdminDashboardFrame() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Toko Buku - Super Admin");
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int option = JOptionPane.showConfirmDialog(
                        SuperAdminDashboardFrame.this,
                        "Apakah Kamu Yakin Ingin Keluar Dari Aplikasi?",
                        "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
                if(option == JOptionPane.YES_OPTION){
                    SuperAdminDashboardFrame.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    LoginFrame loginFrame = new LoginFrame();
                    SuperAdminDashboardFrame.this.setVisible(false);
                    loginFrame.setVisible(true);
                    loginFrame.requestFocus();
                } else {
                    SuperAdminDashboardFrame.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ChangePassword = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MaintenancePegawaiMenu = new javax.swing.JMenuItem();
        MaintenanceRolePegawaiMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        JMenuBuku = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\User\\Documents\\kuliah\\semester4\\pemrograman_desktop\\project\\toko_buku\\Fix_Tubes\\assets\\images\\dashboard-img-scale.jpg")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1200, 690));

        jMenuBar1.setBackground(new java.awt.Color(84, 119, 146));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("File");

        ChangePassword.setBackground(new java.awt.Color(84, 119, 146));
        ChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        ChangePassword.setText("Ganti Password");
        ChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordActionPerformed(evt);
            }
        });
        jMenu1.add(ChangePassword);

        Exit.setBackground(new java.awt.Color(84, 119, 146));
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("Keluar");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Edit");

        MaintenancePegawaiMenu.setBackground(new java.awt.Color(84, 119, 146));
        MaintenancePegawaiMenu.setForeground(new java.awt.Color(255, 255, 255));
        MaintenancePegawaiMenu.setText("Maintenance Pegawai");
        MaintenancePegawaiMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaintenancePegawaiMenuActionPerformed(evt);
            }
        });
        jMenu3.add(MaintenancePegawaiMenu);

        MaintenanceRolePegawaiMenu.setBackground(new java.awt.Color(84, 119, 146));
        MaintenanceRolePegawaiMenu.setForeground(new java.awt.Color(255, 255, 255));
        MaintenanceRolePegawaiMenu.setText("Maintenance Role Pegawai");
        MaintenanceRolePegawaiMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaintenanceRolePegawaiMenuActionPerformed(evt);
            }
        });
        jMenu3.add(MaintenanceRolePegawaiMenu);

        jMenuBar1.add(jMenu3);

        jMenu2.setBackground(new java.awt.Color(33, 52, 72));
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Master Data");

        jMenuItem9.setBackground(new java.awt.Color(84, 119, 146));
        jMenuItem9.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem9.setText("Detail Buku");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setBackground(new java.awt.Color(84, 119, 146));
        jMenuItem10.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem10.setText("Konfigurasi Data Vendor");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        JMenuBuku.setBackground(new java.awt.Color(84, 119, 146));
        JMenuBuku.setForeground(new java.awt.Color(33, 52, 72));
        JMenuBuku.setText("Buku");

        jMenuItem5.setBackground(new java.awt.Color(84, 119, 146));
        jMenuItem5.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem5.setText("Data Master Buku");
        JMenuBuku.add(jMenuItem5);

        jMenuItem6.setBackground(new java.awt.Color(84, 119, 146));
        jMenuItem6.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem6.setText("Data Kategori Buku");
        JMenuBuku.add(jMenuItem6);

        jMenuItem7.setBackground(new java.awt.Color(84, 119, 146));
        jMenuItem7.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem7.setText("Data  Penerbit");
        JMenuBuku.add(jMenuItem7);

        jMenuItem8.setBackground(new java.awt.Color(84, 119, 146));
        jMenuItem8.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem8.setText("Data Pengarang");
        JMenuBuku.add(jMenuItem8);

        jMenu2.add(JMenuBuku);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Apakah Kamu Yakin Ingin Keluar Dari Akun?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.setVisible(false);
            LoginFrame loginFrame = new LoginFrame();
            loginFrame.setVisible(true);
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void ChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordActionPerformed
        ChangePassword changePassword = new ChangePassword();
        changePassword.setVisible(true);
        changePassword.requestFocus();
    }//GEN-LAST:event_ChangePasswordActionPerformed

    private void MaintenanceRolePegawaiMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaintenanceRolePegawaiMenuActionPerformed
        MaintenanceRolePegawai maintenanceRolePegawai = new MaintenanceRolePegawai(this);
        maintenanceRolePegawai.setVisible(true);
        maintenanceRolePegawai.requestFocus();
        this.setEnabled(false);
    }//GEN-LAST:event_MaintenanceRolePegawaiMenuActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void MaintenancePegawaiMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaintenancePegawaiMenuActionPerformed
        MaintenancePegawai maintenancePegawai = new MaintenancePegawai(this);
        maintenancePegawai.setVisible(true);
        maintenancePegawai.requestFocus();
        this.setEnabled(false);
    }//GEN-LAST:event_MaintenancePegawaiMenuActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ChangePassword;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu JMenuBuku;
    private javax.swing.JMenuItem MaintenancePegawaiMenu;
    private javax.swing.JMenuItem MaintenanceRolePegawaiMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
