/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uas_pemrograman_desktop;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author rifki
 */
public class ConfigProdukFrame extends javax.swing.JFrame {
    private DefaultTableModel dtm;
    private MenuUtamaFrame muf;
    /**
     * Creates new form ConfigProdukFrame
     */
    public ConfigProdukFrame(MenuUtamaFrame muf) {
        this.muf = muf;
        
        initComponents();
        
        setHeaderTable();
        
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int option = JOptionPane.showConfirmDialog(ConfigProdukFrame.this,
                        "Apakah Kamu Yakin Ingin Keluar Dari Config Produk?",
                        "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
                if(option == JOptionPane.YES_OPTION){
                    ConfigProdukFrame.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    ConfigProdukFrame.this.setVisible(false);
                    muf.setVisible(true);
                    muf.requestFocus();
                }
            }
        });
    }
    
        private void setColSize(){
        TableColumn column;
        jTableProduk.setAutoResizeMode(jTableProduk.AUTO_RESIZE_OFF);
        column = jTableProduk.getColumnModel().getColumn(0);
        column.setPreferredWidth(250);
        column = jTableProduk.getColumnModel().getColumn(1);
        column.setPreferredWidth(250);
        column = jTableProduk.getColumnModel().getColumn(2);
        column.setPreferredWidth(250);
        column = jTableProduk.getColumnModel().getColumn(3);
        column.setPreferredWidth(250);
    }
    
    private void setDataTable(){
        try{
            DbConnection dbc = new DbConnection();
            
            String query = "SELECT * FROM tmasterid"; 
            PreparedStatement pstmt = dbc.getConnection().prepareStatement(query);
            ResultSet rslt = pstmt.executeQuery();
                    
            dtm.setRowCount(0);
            
            while (rslt.next()) {    
            Object[] fieldx = new Object[4];
                fieldx[0] = rslt.getString("itemid");
                fieldx[1] = rslt.getString("namaproduk");
                fieldx[2] = rslt.getString("price");
                fieldx[3] = rslt.getString("totalstok");
                dtm.addRow(fieldx);
            }
        } catch (SQLException  e){
            e.printStackTrace();
        }
    }
    
    private void setHeaderTable(){
        this.dtm = new DefaultTableModel();
        jTableProduk.setModel(dtm);
        dtm.addColumn("Item ID");
        dtm.addColumn("Nama Produk");
        dtm.addColumn("Harga");
        dtm.addColumn("total Stok");
        
        setColSize();
        setDataTable();
    }
    
    private void clearInput(){
        jTextFieldIdProduk.setText("");
        jTextFieldNamaProduk.setText("");
        jTextFieldPriceProduk.setText("");
        jTextFieldTotalStockProduk.setText("");
        
        jButtonSimpan.setText("Simpan");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIdProduk = new javax.swing.JTextField();
        jTextFieldNamaProduk = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTotalStockProduk = new javax.swing.JTextField();
        jButtonSimpan = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonResetInput = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPriceProduk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonAddNewItemID = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduk = new javax.swing.JTable();
        jButtonKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 40, 49));

        jPanel2.setBackground(new java.awt.Color(57, 62, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Produk");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item ID");

        jTextFieldIdProduk.setEditable(false);
        jTextFieldIdProduk.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Stock");

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonResetInput.setText("Reset");
        jButtonResetInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetInputActionPerformed(evt);
            }
        });

        jLabel5.setText(" ");

        jLabel6.setText(" ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Config Produk");

        jLabel8.setText(" ");

        jLabel9.setText(" ");

        jLabel10.setText(" ");

        jLabel11.setText(" ");

        jButtonAddNewItemID.setText("Tambahkan item ID");
        jButtonAddNewItemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewItemIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                                                .addGap(0, 310, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jButtonAddNewItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldTotalStockProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextFieldPriceProduk, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(336, 336, 336)))
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 4, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldIdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonResetInput, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldIdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPriceProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAddNewItemID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTotalStockProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonSimpan)
                                    .addComponent(jButtonHapus)
                                    .addComponent(jButtonResetInput)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, Short.MAX_VALUE))
        );

        jTableProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item ID", "Nama Produk", "Price", "Total Stock"
            }
        ));
        jTableProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProduk);

        jButtonKeluar.setText("Keluar");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonKeluar)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonKeluar)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        try{
            String idProduk = jTextFieldIdProduk.getText();
            String namaProduk = jTextFieldNamaProduk.getText();
            String hargaProduk = jTextFieldPriceProduk.getText();
            String totalStokProduk = jTextFieldTotalStockProduk.getText();

            DbConnection dbc = new DbConnection();

            if(idProduk.equals("")){
                JOptionPane.showMessageDialog(this, "id Produk Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if(namaProduk.equals("")){
                JOptionPane.showMessageDialog(this, "Nama Produk Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if(hargaProduk.equals("")){
                JOptionPane.showMessageDialog(this, "Harga Produk Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if(totalStokProduk.equals("")){
                JOptionPane.showMessageDialog(this, "Total Stok Produk Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {

                // check first
                String queryCheck = "SELECT *FROM tmasterid WHERE itemid = ?";
                PreparedStatement pstmt = dbc.getConnection().prepareStatement(queryCheck);
                pstmt.setString(1, idProduk);
                ResultSet rslt = pstmt.executeQuery();

                if(rslt.next()){

                    if(JOptionPane.showConfirmDialog(this, "Produk sudah ada, apakah yakin ingin update data Produk?", "konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){

                        String queryUpdate = "UPDATE tmasterid SET namaproduk = ?, price = ?, totalstok = ? WHERE itemid = ?";
                        pstmt = dbc.getConnection().prepareStatement(queryUpdate);
                        pstmt.setString(1, namaProduk);
                        pstmt.setString(2, hargaProduk);
                        pstmt.setString(3, totalStokProduk);
                        pstmt.setString(4, idProduk);

                        int affected = pstmt.executeUpdate();

                        if(affected > 0){
                            clearInput();
                            setDataTable();
                            JOptionPane.showMessageDialog(this, "Data Produk berhasil di Update!", "informasi", JOptionPane.INFORMATION_MESSAGE);
                        }

                    }
                } else {

                    String queryInsert = "INSERT INTO tmasterid(itemid, namaproduk, price, totalstok) values(?, ?, ?, ?)";
                    pstmt = dbc.getConnection().prepareStatement(queryInsert);
                    pstmt.setString(1, idProduk);
                    pstmt.setString(2, namaProduk);
                    pstmt.setString(3, hargaProduk);
                    pstmt.setString(4, totalStokProduk);

                    int affected = pstmt.executeUpdate();

                    if(affected > 0){
                        clearInput();
                        setDataTable();
                        JOptionPane.showMessageDialog(this, "Data Produk berhasil di Tambahkan!", "informasi", JOptionPane.INFORMATION_MESSAGE);
                    }

                }
            }

        } catch (SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        try{
            String idProduk = jTextFieldIdProduk.getText();
            String namaProduk = jTextFieldNamaProduk.getText();
            String hargaProduk = jTextFieldPriceProduk.getText();
            String totalStokProduk = jTextFieldTotalStockProduk.getText();

            DbConnection dbc = new DbConnection();

            if(idProduk.equals("")){
                JOptionPane.showMessageDialog(this, "id Produk Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if(namaProduk.equals("")){
                JOptionPane.showMessageDialog(this, "Nama Produk Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if(hargaProduk.equals("")){
                JOptionPane.showMessageDialog(this, "Harga Produk Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if(totalStokProduk.equals("")){
                JOptionPane.showMessageDialog(this, "Total Stok Produk Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {

                // check first
                String queryCheck = "SELECT *FROM tmasterid WHERE itemid = ?";
                PreparedStatement pstmt = dbc.getConnection().prepareStatement(queryCheck);
                pstmt.setString(1, idProduk);
                ResultSet rslt = pstmt.executeQuery();

                if(rslt.next()){

                    if(JOptionPane.showConfirmDialog(this, "Produk Ditemukan, apakah yakin ingin Menghapus data Produk?", "konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){

                        String queryDelete = "DELETE FROM tmasterid WHERE itemid = ?";
                        pstmt = dbc.getConnection().prepareStatement(queryDelete);
                        pstmt.setString(1, idProduk);

                        int affected = pstmt.executeUpdate();

                        if(affected > 0){
                            clearInput();
                            setDataTable();
                            JOptionPane.showMessageDialog(this, "Data Produk berhasil di Hapus!", "informasi", JOptionPane.INFORMATION_MESSAGE);
                        }

                    }
                } else {

                    clearInput();
                    JOptionPane.showMessageDialog(this, "Produk Tidak Ditemukan", "warning", JOptionPane.WARNING_MESSAGE);

                }
            }

        } catch (SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonResetInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetInputActionPerformed
        clearInput();
    }//GEN-LAST:event_jButtonResetInputActionPerformed

    private void jTableProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdukMouseClicked
        jTextFieldIdProduk.setText(dtm.getValueAt(jTableProduk.getSelectedRow(), 0) + "");
        jTextFieldNamaProduk.setText(dtm.getValueAt(jTableProduk.getSelectedRow(), 1) + "");
        jTextFieldPriceProduk.setText(dtm.getValueAt(jTableProduk.getSelectedRow(), 2) + "");
        jTextFieldTotalStockProduk.setText(dtm.getValueAt(jTableProduk.getSelectedRow(), 3) + "");

        jButtonSimpan.setText("Update");
    }//GEN-LAST:event_jTableProdukMouseClicked

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Apakah Kamu Yakin Untuk Keluar?", "konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.setVisible(false);
            this.muf.setVisible(true);
            this.muf.requestFocus();
        }
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void jButtonAddNewItemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewItemIDActionPerformed
        try{
            DbConnection dbc = new DbConnection();
            
            jTextFieldIdProduk.setText("");
            
            if(jTextFieldIdProduk.getText().trim().isEmpty()){
                String queryCount = "SELECT COUNT(*) FROM tmasterid WHERE itemid = ?";
                PreparedStatement pstmt = dbc.getConnection().prepareStatement(queryCount);

                String prefix = "PRD";
                int counter = 1;
                String newId;

                while(true){
                    newId = prefix + String.format("%03d", counter);
                    pstmt.setString(1, newId);
                    ResultSet rslt = pstmt.executeQuery();

                    boolean exists = false;
                    if(rslt.next()){
                        exists = rslt.getInt(1) > 0;
                    }

                    if(exists == false){
                        break;
                    }
                    counter++;
                }
                jTextFieldIdProduk.setText(newId);   
            }
        } catch (SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonAddNewItemIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddNewItemID;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonResetInput;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProduk;
    private javax.swing.JTextField jTextFieldIdProduk;
    private javax.swing.JTextField jTextFieldNamaProduk;
    private javax.swing.JTextField jTextFieldPriceProduk;
    private javax.swing.JTextField jTextFieldTotalStockProduk;
    // End of variables declaration//GEN-END:variables
}
