/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uas_pemrograman_desktop;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author rifki
 */
public class ConfigSupplierFrame extends javax.swing.JFrame {
    private DefaultTableModel dtm;
    private MenuUtamaFrame muf;
    /**
     * Creates new form VendorFrame
     */
    public ConfigSupplierFrame(MenuUtamaFrame muf) {
        this.muf = muf;
        
        initComponents();
        
        setHeaderTable();
        
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int option = JOptionPane.showConfirmDialog(ConfigSupplierFrame.this,
                        "Apakah Kamu Yakin Ingin Keluar Dari Aplikasi?",
                        "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
                if(option == JOptionPane.YES_OPTION){
                    ConfigSupplierFrame.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    ConfigSupplierFrame.this.setVisible(false);
                    muf.setVisible(true);
                    muf.requestFocus();
                }
            }
        });
    }
    
    private void setColSize(){
        TableColumn column;
        jTableSupplier.setAutoResizeMode(jTableSupplier.AUTO_RESIZE_OFF);
        column = jTableSupplier.getColumnModel().getColumn(0);
        column.setPreferredWidth(250);
        column = jTableSupplier.getColumnModel().getColumn(1);
        column.setPreferredWidth(250);
        column = jTableSupplier.getColumnModel().getColumn(2);
        column.setPreferredWidth(250);
        column = jTableSupplier.getColumnModel().getColumn(3);
        column.setPreferredWidth(250);
    }
    
    private void setDataTable(){
        try{
            DbConnection dbc = new DbConnection();
            
            String query = "SELECT * FROM tsupplier"; 
            PreparedStatement pstmt = dbc.getConnection().prepareStatement(query);
            ResultSet rslt = pstmt.executeQuery();
                    
            dtm.setRowCount(0);
            
            while (rslt.next()) {    
            Object[] fieldx = new Object[4];
                fieldx[0] = rslt.getString("kodesupplier");
                fieldx[1] = rslt.getString("namasupplier");
                fieldx[2] = rslt.getString("alamat");
                fieldx[3] = rslt.getString("pic");
                dtm.addRow(fieldx);
            }
        } catch (SQLException  e){
            e.printStackTrace();
        }
    }
    
    private void setHeaderTable(){
        this.dtm = new DefaultTableModel();
        jTableSupplier.setModel(dtm);
        dtm.addColumn("Kode Supplier");
        dtm.addColumn("Nama Supplier");
        dtm.addColumn("Alamat Supplier");
        dtm.addColumn("PIC Supplier");
        
        setColSize();
        setDataTable();
    }
    
    private void clearInput(){
        jTextFieldKodeSupplier.setText("");
        jTextFieldNamaSupplier.setText("");
        jTextAreaAlamatSupplier.setText("");
        jTextFieldPICSupplier.setText("");
        
        jButtonSimpan.setText("Simpan");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldKodeSupplier = new javax.swing.JTextField();
        jTextFieldNamaSupplier = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAlamatSupplier = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPICSupplier = new javax.swing.JTextField();
        jButtonSimpan = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonResetInput = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonNewCodeSupplier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSupplier = new javax.swing.JTable();
        jButtonKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 40, 49));

        jPanel2.setBackground(new java.awt.Color(57, 62, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Supplier");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Supplier");

        jTextFieldKodeSupplier.setEditable(false);
        jTextFieldKodeSupplier.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alamat :");

        jTextAreaAlamatSupplier.setColumns(20);
        jTextAreaAlamatSupplier.setRows(5);
        jScrollPane2.setViewportView(jTextAreaAlamatSupplier);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PIC");

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonResetInput.setText("Reset");
        jButtonResetInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetInputActionPerformed(evt);
            }
        });

        jLabel5.setText(" ");

        jLabel6.setText(" ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Config Supplier");

        jLabel8.setText(" ");

        jLabel10.setText(" ");

        jButtonNewCodeSupplier.setText("Tambahkan Kode Supplier");
        jButtonNewCodeSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCodeSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonResetInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jButtonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPICSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNamaSupplier)
                                    .addComponent(jTextFieldKodeSupplier)
                                    .addComponent(jButtonNewCodeSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(66, 66, 66)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3418, 3418, 3418)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldKodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jButtonNewCodeSupplier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextFieldNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldPICSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSimpan)
                            .addComponent(jButtonHapus)
                            .addComponent(jButtonResetInput)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        jTableSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Supplier", "Nama Supplier", "Alamat", "PIC"
            }
        ));
        jTableSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSupplier);

        jButtonKeluar.setText("Keluar");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonKeluar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 888, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonKeluar)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSupplierMouseClicked
        jTextFieldKodeSupplier.setText(dtm.getValueAt(jTableSupplier.getSelectedRow(), 0) + "");
        jTextFieldNamaSupplier.setText(dtm.getValueAt(jTableSupplier.getSelectedRow(), 1) + "");
        jTextAreaAlamatSupplier.setText(dtm.getValueAt(jTableSupplier.getSelectedRow(), 2) + "");
        jTextFieldPICSupplier.setText(dtm.getValueAt(jTableSupplier.getSelectedRow(), 3) + "");
        
        jButtonSimpan.setText("Update");
    }//GEN-LAST:event_jTableSupplierMouseClicked

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Apakah Kamu Yakin Untuk Keluar?", "konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.setVisible(false);
            muf.setVisible(true);
            muf.requestFocus();
        }
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void jButtonResetInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetInputActionPerformed
        clearInput();
    }//GEN-LAST:event_jButtonResetInputActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        try{
            String kodeSupplier = jTextFieldKodeSupplier.getText();
            String namaSupplier = jTextFieldNamaSupplier.getText();
            String alamatSupplier = jTextAreaAlamatSupplier.getText();
            String PICSupplier = jTextFieldPICSupplier.getText();

            DbConnection dbc = new DbConnection();

            if(kodeSupplier.equals("")){
                JOptionPane.showMessageDialog(this, "Kode Supplier Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if(namaSupplier.equals("")){
                JOptionPane.showMessageDialog(this, "Nama Supplier Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if(alamatSupplier.equals("")){
                JOptionPane.showMessageDialog(this, "Alamat Supplier Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if(PICSupplier.equals("")){
                JOptionPane.showMessageDialog(this, "PIC Supplier Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {

                // check first
                String queryCheck = "SELECT *FROM tsupplier WHERE kodesupplier = ?";
                PreparedStatement pstmt = dbc.getConnection().prepareStatement(queryCheck);
                pstmt.setString(1, kodeSupplier);
                ResultSet rslt = pstmt.executeQuery();

                if(rslt.next()){

                    if(JOptionPane.showConfirmDialog(this, "Supplier Ditemukan, apakah yakin ingin Menghapus data supplier?", "konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){

                        String queryDelete = "DELETE FROM tsupplier WHERE kodesupplier = ?";
                        pstmt = dbc.getConnection().prepareStatement(queryDelete);
                        pstmt.setString(1, kodeSupplier);

                        int affected = pstmt.executeUpdate();

                        if(affected > 0){
                            clearInput();
                            setDataTable();
                            JOptionPane.showMessageDialog(this, "Data Supplier berhasil di Hapus!", "informasi", JOptionPane.INFORMATION_MESSAGE);
                        }

                    }
                } else {

                    clearInput();
                    JOptionPane.showMessageDialog(this, "Supplier Tidak Ditemukan", "warning", JOptionPane.WARNING_MESSAGE);

                }
            }

        } catch (SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        try{
            String kodeSupplier = jTextFieldKodeSupplier.getText();
            String namaSupplier = jTextFieldNamaSupplier.getText();
            String alamatSupplier = jTextAreaAlamatSupplier.getText();
            String PICSupplier = jTextFieldPICSupplier.getText();

            DbConnection dbc = new DbConnection();

            if(kodeSupplier.equals("")){
                JOptionPane.showMessageDialog(this, "Kode Supplier Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if(namaSupplier.equals("")){
                JOptionPane.showMessageDialog(this, "Nama Supplier Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if(alamatSupplier.equals("")){
                JOptionPane.showMessageDialog(this, "Alamat Supplier Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if(PICSupplier.equals("")){
                JOptionPane.showMessageDialog(this, "PIC Supplier Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {

                // check first
                String queryCheck = "SELECT *FROM tsupplier WHERE kodesupplier = ?";
                PreparedStatement pstmt = dbc.getConnection().prepareStatement(queryCheck);
                pstmt.setString(1, kodeSupplier);
                ResultSet rslt = pstmt.executeQuery();

                if(rslt.next()){

                    if(JOptionPane.showConfirmDialog(this, "Supplier sudah ada, apakah yakin ingin update data supplier?", "konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){

                        String queryUpdate = "UPDATE tsupplier SET namasupplier = ?, alamat = ?, pic = ? WHERE kodesupplier = ?";
                        pstmt = dbc.getConnection().prepareStatement(queryUpdate);
                        pstmt.setString(1, namaSupplier);
                        pstmt.setString(2, alamatSupplier);
                        pstmt.setString(3, PICSupplier);
                        pstmt.setString(4, kodeSupplier);

                        int affected = pstmt.executeUpdate();

                        if(affected > 0){
                            clearInput();
                            setDataTable();
                            JOptionPane.showMessageDialog(this, "Data Supplier berhasil di Update!", "informasi", JOptionPane.INFORMATION_MESSAGE);
                        }

                    }
                } else {

                    String queryInsert = "INSERT INTO tsupplier(kodesupplier, namasupplier, alamat, pic) values(?, ?, ?, ?)";
                    pstmt = dbc.getConnection().prepareStatement(queryInsert);
                    pstmt.setString(1, kodeSupplier);
                    pstmt.setString(2, namaSupplier);
                    pstmt.setString(3, alamatSupplier);
                    pstmt.setString(4, PICSupplier);

                    int affected = pstmt.executeUpdate();

                    if(affected > 0){
                        clearInput();
                        setDataTable();
                        JOptionPane.showMessageDialog(this, "Data Supplier berhasil di Tambahkan!", "informasi", JOptionPane.INFORMATION_MESSAGE);
                    }

                }
            }

        } catch (SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonNewCodeSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCodeSupplierActionPerformed
        try{
            DbConnection dbc = new DbConnection();
            
            jTextFieldKodeSupplier.setText("");
            
            if(jTextFieldKodeSupplier.getText().trim().isEmpty()){
                String queryCount = "SELECT COUNT(*) FROM tsupplier WHERE kodesupplier = ?";
                PreparedStatement pstmt = dbc.getConnection().prepareStatement(queryCount);

                String prefix = "SUP";
                int counter = 1;
                String newId;

                while(true){
                    newId = prefix + String.format("%03d", counter);
                    pstmt.setString(1, newId);
                    ResultSet rslt = pstmt.executeQuery();

                    boolean exists = false;
                    if(rslt.next()){
                        exists = rslt.getInt(1) > 0;
                    }

                    if(exists == false){
                        break;
                    }
                    counter++;
                }
                jTextFieldKodeSupplier.setText(newId);   
            }
        } catch (SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonNewCodeSupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonNewCodeSupplier;
    private javax.swing.JButton jButtonResetInput;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSupplier;
    private javax.swing.JTextArea jTextAreaAlamatSupplier;
    private javax.swing.JTextField jTextFieldKodeSupplier;
    private javax.swing.JTextField jTextFieldNamaSupplier;
    private javax.swing.JTextField jTextFieldPICSupplier;
    // End of variables declaration//GEN-END:variables
}
