/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uas_pemrograman_desktop;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author rifki
 */
public class ProductSearchFrame extends javax.swing.JFrame {
    private DefaultTableModel dtm;
    private NewPurchasingOrderFrame npof;
    private String idProduk;
    /**
     * Creates new form ProductSearchFrame
     */
    public ProductSearchFrame(NewPurchasingOrderFrame npof) {
        this.npof = npof;
        
        initComponents();
        
        setHeaderTable();
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int option = JOptionPane.showConfirmDialog(ProductSearchFrame.this,
                        "Apakah Yakin Ingin Keluar",
                        "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
                if(option == JOptionPane.YES_OPTION){
                    ProductSearchFrame.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    ProductSearchFrame.this.setVisible(false);
                    npof.setEnabled(true);
                    npof.requestFocus();
                } else {
                    ProductSearchFrame.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }
            }
        });
    }
    
    private void setColSize(){
        TableColumn column;
        jTableSupplier.setAutoResizeMode(jTableSupplier.AUTO_RESIZE_OFF);
        column = jTableSupplier.getColumnModel().getColumn(0);
        column.setPreferredWidth(150);
        column = jTableSupplier.getColumnModel().getColumn(1);
        column.setPreferredWidth(250);
        column = jTableSupplier.getColumnModel().getColumn(2);
        column.setPreferredWidth(150);
        column = jTableSupplier.getColumnModel().getColumn(3);
        column.setPreferredWidth(150);
        column = jTableSupplier.getColumnModel().getColumn(4);
        column.setPreferredWidth(150);
        column = jTableSupplier.getColumnModel().getColumn(5);
        column.setPreferredWidth(150);
        column = jTableSupplier.getColumnModel().getColumn(6);
        column.setPreferredWidth(200);
        column = jTableSupplier.getColumnModel().getColumn(7);
        column.setPreferredWidth(250);
    }
    
    private void setDataTable(){
        try{
            DbConnection dbc = new DbConnection();
            
            String querySelect = "SELECT a.*, b.kodesupplier, b.namasupplier, c.namaproduk FROM tdetailproduk a JOIN tsupplier b ON a.kodesupplier = b.kodesupplier JOIN tmasterid ON a.itemid = c.itemid"; 
            PreparedStatement pstmt = dbc.getConnection().prepareStatement(querySelect);
            ResultSet rslt = pstmt.executeQuery();
                    
            dtm.setRowCount(0);
            
            while (rslt.next()) {    
                Object[] fieldx = new Object[8];
                fieldx[0] = rslt.getString("itemid");
                fieldx[1] = rslt.getString("namaproduk");
                fieldx[2] = rslt.getString("price");
                fieldx[3] = rslt.getString("disc");
                fieldx[4] = rslt.getString("costprice");
                fieldx[5] = rslt.getString("instock");
                fieldx[6] = rslt.getString("kodesupplier");
                fieldx[7] = rslt.getString("namasupplier");
                dtm.addRow(fieldx);
            }
        } catch (SQLException  e){
            e.printStackTrace();
        }
    }
    
    private void setHeaderTable(){
        this.dtm = new DefaultTableModel();
        jTableSupplier.setModel(dtm);
        dtm.addColumn("ID Produk");
        dtm.addColumn("Nama Produk");
        dtm.addColumn("Harga");
        dtm.addColumn("Diskon");
        dtm.addColumn("Cost Price");
        dtm.addColumn("Instock");
        dtm.addColumn("Kode Supplier");
        dtm.addColumn("namasupplier");
        
        setColSize();
        setDataTable();
    }
    
    public String getIdProduk() {
        return idProduk;
    }

    public void setIdProduk(String idProduk) {
        this.idProduk = idProduk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPencarianNamaProduk = new javax.swing.JTextField();
        jTextFieldIdProduk = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProduk = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(57, 62, 70));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pencarian Produk");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cari Nama :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID Porduk");

        jTextFieldPencarianNamaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPencarianNamaProdukActionPerformed(evt);
            }
        });

        jTextFieldIdProduk.setEditable(false);
        jTextFieldIdProduk.setEnabled(false);

        jTableProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Produk", "Nama Produk", "Harga", "Diskon", "Cost Price", "Instock", "Kode Supplier", "Nama Supplier"
            }
        ));
        jTableProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdukMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableProduk);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPencarianNamaProduk)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldPencarianNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPencarianNamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPencarianNamaProdukActionPerformed
        try {
            String namaProduk = jTextFieldPencarianNamaProduk.getText().trim();  // Input dari user
            DbConnection dbc = new DbConnection();

            dtm.setRowCount(0); // Bersihkan isi tabel

            if (namaProduk.isEmpty()) {
                setDataTable();  // Tampilkan semua jika kosong
            } else {
                String query = "SELECT a.*, b.kodesupplier, b.namasupplier, c.namaproduk " +
                               "FROM tdetailproduk a " +
                               "JOIN tsupplier b ON a.kodesupplier = b.kodesupplier " +
                               "JOIN tmasterid c ON a.itemid = c.itemid " +
                               "WHERE a.itemid LIKE ? OR c.namaproduk LIKE ? " +
                               "ORDER BY b.kodesupplier ASC";

                PreparedStatement pstmt = dbc.getConnection().prepareStatement(query);
                pstmt.setString(1, "%" + namaProduk + "%"); // Bisa cocokkan ItemID
                pstmt.setString(2, "%" + namaProduk + "%"); // Atau NamaProduk

                ResultSet rslt = pstmt.executeQuery();

                if (rslt.isBeforeFirst()) {
                    while (rslt.next()) {
                        Object[] fieldx = new Object[8];
                        fieldx[0] = rslt.getString("itemid");
                        fieldx[1] = rslt.getString("namaproduk");
                        fieldx[2] = rslt.getString("price");
                        fieldx[3] = rslt.getString("disc");
                        fieldx[4] = rslt.getString("costprice");
                        fieldx[5] = rslt.getString("instock");
                        fieldx[6] = rslt.getString("kodesupplier");
                        fieldx[7] = rslt.getString("namasupplier");
                        dtm.addRow(fieldx);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Produk tidak ditemukan!", "Pencarian", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        } 
    }//GEN-LAST:event_jTextFieldPencarianNamaProdukActionPerformed

    private void jTableProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdukMouseClicked
        this.npof.setKodeSupplier(dtm.getValueAt(jTableProduk.getSelectedRow(), 0) + "");
        this.npof.setNamaSupplier(dtm.getValueAt(jTableProduk.getSelectedRow(), 1) + "");
        this.npof.setAlamatSupplier(dtm.getValueAt(jTableProduk.getSelectedRow(), 2) + "");
        this.npof.setPicSupplier(dtm.getValueAt(jTableProduk.getSelectedRow(), 3) + "");
        //  FIXME
        jTextFieldKodeSupplier.setText(dtm.getValueAt(jTableProduk.getSelectedRow(), 0) + "");
    }//GEN-LAST:event_jTableProdukMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableProduk;
    private javax.swing.JTable jTableSupplier;
    private javax.swing.JTable jTableSupplier1;
    private javax.swing.JTextField jTextFieldIdProduk;
    private javax.swing.JTextField jTextFieldKodeSupplier;
    private javax.swing.JTextField jTextFieldKodeSupplier1;
    private javax.swing.JTextField jTextFieldPencarianNamaProduk;
    private javax.swing.JTextField jTextFieldSupplierSearchBar;
    private javax.swing.JTextField jTextFieldSupplierSearchBar1;
    // End of variables declaration//GEN-END:variables
}
