/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uas_pemrograman_desktop;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author rifki
 */
public class SupplierSearchFrame extends javax.swing.JFrame {
    private DefaultTableModel dtm;
    private String kodeSupplier;
    private NewPurchasingOrderFrame npof;
    /**
     * Creates new form VendorSearchFrame
     */
    public SupplierSearchFrame(NewPurchasingOrderFrame npof) {
        this.npof = npof;
        
        initComponents();
        
        setHeaderTable();
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int option = JOptionPane.showConfirmDialog(SupplierSearchFrame.this,
                        "Apakah Yakin Ingin Keluar Dari Menu Pencarian",
                        "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
                if(option == JOptionPane.YES_OPTION){
                    SupplierSearchFrame.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    SupplierSearchFrame.this.setVisible(false);
                    npof.setEnabled(true);
                    npof.requestFocus();
                } else {
                    SupplierSearchFrame.this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                }
            }
        });
    }
    
    private void setColSize(){
        TableColumn column;
        jTableSupplier.setAutoResizeMode(jTableSupplier.AUTO_RESIZE_OFF);
        column = jTableSupplier.getColumnModel().getColumn(0);
        column.setPreferredWidth(100);
        column = jTableSupplier.getColumnModel().getColumn(1);
        column.setPreferredWidth(200);
        column = jTableSupplier.getColumnModel().getColumn(2);
        column.setPreferredWidth(200);
        column = jTableSupplier.getColumnModel().getColumn(3);
        column.setPreferredWidth(200);
    }
    
    private void setDataTable(){
        try{
            DbConnection dbc = new DbConnection();
            
            String query = "SELECT * FROM tsupplier"; 
            PreparedStatement pstmt = dbc.getConnection().prepareStatement(query);
            ResultSet rslt = pstmt.executeQuery();
                    
            dtm.setRowCount(0);
            
            while (rslt.next()) {    
                Object[] fieldx = new Object[4];
                fieldx[0] = rslt.getString("kodesupplier");
                fieldx[1] = rslt.getString("namasupplier");
                fieldx[2] = rslt.getString("alamat");
                fieldx[3] = rslt.getString("pic");
                dtm.addRow(fieldx);
            }
        } catch (SQLException  e){
            e.printStackTrace();
        }
    }
    
    private void setHeaderTable(){
        this.dtm = new DefaultTableModel();
        jTableSupplier.setModel(dtm);
        dtm.addColumn("Kode Supplier");
        dtm.addColumn("Nama Supplier");
        dtm.addColumn("Alamat Supplier");
        dtm.addColumn("PIC Supplier");
        
        setColSize();
        setDataTable();
    }

    public String getKodeSupplier() {
        return kodeSupplier;
    }

    public void setKodeSupplier(String supplierId) {
        this.kodeSupplier = supplierId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSupplierSearchBar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldKodeSupplier = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSupplier = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(57, 62, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pencarian Supplier");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cari Nama");

        jTextFieldSupplierSearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSupplierSearchBarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kode Supplier");

        jTextFieldKodeSupplier.setEditable(false);
        jTextFieldKodeSupplier.setEnabled(false);
        jTextFieldKodeSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKodeSupplierActionPerformed(evt);
            }
        });

        jTableSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Supplier", "Nama Supplier", "Alamat", "PIC"
            }
        ));
        jTableSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSupplier);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSupplierSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldKodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldSupplierSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldKodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSupplierSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSupplierSearchBarActionPerformed
        try {
            jTextFieldKodeSupplier.setText(getKodeSupplier());
            String kodeSupplier = jTextFieldKodeSupplier.getText().trim();
            String namaSupplier = jTextFieldSupplierSearchBar.getText().trim();
            DbConnection dbc = new DbConnection();
            
            dtm.setRowCount(0);
            
            if(namaSupplier.isEmpty()){
                setDataTable();
            } else{
                String queryLike = "SELECT *FROM tsupplier WHERE kodesupplier = ? OR namasupplier LIKE ? ORDER BY kodesupplier ASC";
                PreparedStatement pstmt = dbc.getConnection().prepareStatement(queryLike);
                pstmt.setString(1, "%" + kodeSupplier + "%");
                pstmt.setString(2, "%" + namaSupplier + "%");
                ResultSet rslt = pstmt.executeQuery();
                
                if(rslt.isBeforeFirst()){
                    while(rslt.next()){
                        Object[] fieldx = new Object[4];
                        fieldx[0] = rslt.getString("kodesupplier");
                        fieldx[1] = rslt.getString("namasupplier");
                        fieldx[2] = rslt.getString("alamat");
                        fieldx[3] = rslt.getString("pic");
                        dtm.addRow(fieldx);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Supplier Tidak Ditemukan!", "Not Found", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
        } catch (SQLException ex){
            ex.printStackTrace();
        }     
    }//GEN-LAST:event_jTextFieldSupplierSearchBarActionPerformed

    private void jTableSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSupplierMouseClicked
        this.npof.setKodeSupplier(dtm.getValueAt(jTableSupplier.getSelectedRow(), 0) + "");
        this.npof.setNamaSupplier(dtm.getValueAt(jTableSupplier.getSelectedRow(), 1) + "");
        this.npof.setAlamatSupplier(dtm.getValueAt(jTableSupplier.getSelectedRow(), 2) + "");
        this.npof.setPicSupplier(dtm.getValueAt(jTableSupplier.getSelectedRow(), 3) + "");
        
        jTextFieldKodeSupplier.setText(dtm.getValueAt(jTableSupplier.getSelectedRow(), 0) + "");
    }//GEN-LAST:event_jTableSupplierMouseClicked

    private void jTextFieldKodeSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKodeSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKodeSupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSupplier;
    private javax.swing.JTextField jTextFieldKodeSupplier;
    private javax.swing.JTextField jTextFieldSupplierSearchBar;
    // End of variables declaration//GEN-END:variables
}
