/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bookstore.ui.administrator_menu;

import com.bookstore.data.QuerySelector;
import com.bookstore.ui.SuperAdminDashboardFrame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author rifki
 */
public class ConfigVendor extends javax.swing.JFrame {
    SuperAdminDashboardFrame superAdminDashboardFrame;
    DefaultTableModel model;
    QuerySelector querySelector;
    /**
     * Creates new form ConfigVendor
     */
    public ConfigVendor(SuperAdminDashboardFrame superAdminDashboardFrame) {
        this.superAdminDashboardFrame = superAdminDashboardFrame;
        
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Toko Buku - Maintenance Role Pegawai");
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int option = JOptionPane.showConfirmDialog(
                        ConfigVendor.this,
                        "Apakah Kamu Yakin Ingin Keluar Dari Aplikasi?",
                        "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
                if(option == JOptionPane.YES_OPTION){
                    ConfigVendor.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    ConfigVendor.this.setVisible(false);
                    superAdminDashboardFrame.setEnabled(true);
                    superAdminDashboardFrame.requestFocus();
                } else {
                    ConfigVendor.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }
            }
        });
        
        setHeaderTable();
    }
    
    public void dataVendorToTabel(){
        this.querySelector = new QuerySelector();

        try{
            querySelector.selectAllFromTable("T_Vendor");

            model.setRowCount(0);
            
            while (querySelector.getResultSet().next()) {    
            Object[] fieldx = new Object[4];
                fieldx[0] = querySelector.getResultSet().getString("id_vendor");
                fieldx[1] = querySelector.getResultSet().getString("Nama_vendor");
                fieldx[2] = querySelector.getResultSet().getString("alamat_vendor");
                fieldx[3] = querySelector.getResultSet().getString("kontak_vendor");
                model.addRow(fieldx);
            }
        } catch (SQLException | ClassNotFoundException  e){
            e.printStackTrace();
        }
    }
    
    private void columnWrapping(){
        TableColumn column;
        dataVendorTable.setAutoResizeMode(dataVendorTable.AUTO_RESIZE_OFF);
        column = dataVendorTable.getColumnModel().getColumn(0);
        column.setPreferredWidth(150);
        column = dataVendorTable.getColumnModel().getColumn(1);
        column.setPreferredWidth(250);
        column = dataVendorTable.getColumnModel().getColumn(2);
        column.setPreferredWidth(250);
        column = dataVendorTable.getColumnModel().getColumn(2);
        column.setPreferredWidth(250);
    }

    
    private void setHeaderTable(){
        model = new DefaultTableModel();
        dataVendorTable.setModel(model);
        model.addColumn("Id Vendor");
        model.addColumn("Nama Vendor");
        model.addColumn("Alamat Vendor");
        model.addColumn("Kontak vendor");
        

        columnWrapping();
        dataVendorToTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        field_id_vendor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataVendorTable = new javax.swing.JTable();
        addVendorButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        deleteVendorButon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        field_nama_vendor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        field_alamat_vendor = new javax.swing.JTextField();
        field_kontak_vendor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(84, 119, 146));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Vendor");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Vendor");

        dataVendorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Vendor", "Nama Vendor", "Alamat Vendor", "Kontak Vendor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        dataVendorTable.setShowGrid(true);
        dataVendorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataVendorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataVendorTable);

        addVendorButton.setBackground(new java.awt.Color(33, 52, 72));
        addVendorButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addVendorButton.setForeground(new java.awt.Color(255, 255, 255));
        addVendorButton.setText("Tambahkan");
        addVendorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVendorButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(33, 52, 72));
        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Keluar");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        deleteVendorButon.setBackground(new java.awt.Color(33, 52, 72));
        deleteVendorButon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteVendorButon.setForeground(new java.awt.Color(255, 255, 255));
        deleteVendorButon.setText("Hapus");
        deleteVendorButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVendorButonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Vendor");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alamat Vendor");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kontak Vendor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(field_kontak_vendor, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                                    .addComponent(field_alamat_vendor)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(field_id_vendor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(field_nama_vendor))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(exitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addVendorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteVendorButon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(field_id_vendor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_nama_vendor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_alamat_vendor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_kontak_vendor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(addVendorButton)
                    .addComponent(deleteVendorButon))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataVendorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataVendorTableMouseClicked
        field_id_vendor.setText(model.getValueAt(dataVendorTable.getSelectedRow(), 0) + "");
        field_nama_vendor.setText(model.getValueAt(dataVendorTable.getSelectedRow(), 1) + "");
    }//GEN-LAST:event_dataVendorTableMouseClicked

    private void addVendorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVendorButtonActionPerformed
        String vendorId = field_id_vendor.getText().trim();
        String vendorName = field_nama_vendor.getText().trim();
        String vendorContact = field_kontak_vendor.getText().trim();
        String vendorAddress = field_alamat_vendor.getText().trim();
        
        try {
            if (vendorId.isEmpty() || vendorName.isEmpty() || vendorContact.isEmpty() || vendorAddress.isEmpty()) {
                JOptionPane.showMessageDialog(null, "ID atau Nama Role masih kosong!");
                field_id_vendor.requestFocus();
                return;
            }
            querySelector.countDataByColumn("T_Vendor", "id_vendor", vendorId);

                if (querySelector.getAffectedRows() > 0) {
                    if(JOptionPane.showConfirmDialog(this, "Data Vendor Sudah Ada! Apakah Kamu mau Uodate Data ini?", "info", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                        field_id_vendor.setEnabled(false);
                        
                        querySelector.updateThreeColumns("T_Vendor", "nama_vendor", vendorName, "kontak_vendor", vendorContact, "alamat_vendor", vendorAddress, "id_vendor", vendorId);
                        
                        if (querySelector.getAffectedRows() > 0) {
                            field_id_vendor.setText("");
                            field_nama_vendor.setText("");
                            field_kontak_vendor.setText("");
                            field_alamat_vendor.setText("");
                            
                            dataVendorToTabel();
                            field_id_vendor.setEnabled(true);
                            JOptionPane.showMessageDialog(null, "Data Berhasil Diperbarui");
                        } else {
                            JOptionPane.showMessageDialog(null, "Data Gagal Diperbarui");
                        }
                    }
                } else {
                    querySelector.insertFourColumns("T_Vendor", "id_vendor", "nama_vendor", "alamat_vendor", "kontak_vendor", vendorId, vendorName, vendorContact, vendorAddress);

                    if (querySelector.getAffectedRows() > 0) {
                        model.getDataVector().removeAllElements();
                        model.fireTableDataChanged();
          
                        field_id_vendor.setText("");
                        field_nama_vendor.setText("");
                        field_kontak_vendor.setText("");
                        field_alamat_vendor.setText("");

                       dataVendorToTabel();
                        
                        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                    } else {
                        JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
                    }
                }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "SQL Error: " + e.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MaintenanceRolePegawai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addVendorButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Apakah Kamu Yakin Ingin Keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.setVisible(false);
            superAdminDashboardFrame.setEnabled(true);
            superAdminDashboardFrame.requestFocus();
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void deleteVendorButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVendorButonActionPerformed
        int deleting = JOptionPane.showConfirmDialog(this, "Apakah Kamu Yakin Ingin Menghapus Data Ini?");
        if(deleting == JOptionPane.YES_OPTION){
            String idRole = field_id_vendor.getText().trim();
            if(idRole.isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Role Masih Kosong!");
                field_id_vendor.requestFocus();
            } else {
                try {

                    querySelector.deleteByKey("T_Role", "id_role", idRole);

                    if (querySelector.getAffectedRows() > 0) {
                        model.getDataVector().removeAllElements();
                        model.fireTableDataChanged();

                        field_id_vendor.setText("");
                        field_nama_vendor.setText("");
                        field_kontak_vendor.setText("");
                        field_alamat_vendor.setText("");
                        
                        dataVendorToTabel();
                        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    } else {
                        JOptionPane.showMessageDialog(null, "Vendor Tidak Ada!");
                    }
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(MaintenanceRolePegawai.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "data Berhasil Dihapus");
        }
    }//GEN-LAST:event_deleteVendorButonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVendorButton;
    private javax.swing.JTable dataVendorTable;
    private javax.swing.JButton deleteVendorButon;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField field_alamat_vendor;
    private javax.swing.JTextField field_id_vendor;
    private javax.swing.JTextField field_kontak_vendor;
    private javax.swing.JTextField field_nama_vendor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
