package com.bookstore.ui.administrator_menu;

import com.bookstore.model.Role;
import com.bookstore.ui.JFrameAdmin;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.table.TableColumn;
/**
 *
 * @author rifki
 */
public class JFrameMaintenanceRolePegawai extends javax.swing.JFrame {
    public DefaultTableModel model;
    JFrameAdmin superAdminDashboardFrame;
    /**
     * Creates new form MaintenanceRolePegawai
     * @param superAdminDashboardFrame
     */
    public JFrameMaintenanceRolePegawai(JFrameAdmin superAdminDashboardFrame) {
        this.superAdminDashboardFrame = superAdminDashboardFrame;
        
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Toko Buku - Maintenance Role Pegawai");
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int option = JOptionPane.showConfirmDialog(JFrameMaintenanceRolePegawai.this,
                        "Apakah Kamu Yakin Ingin Keluar Dari Aplikasi?",
                        "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
                if(option == JOptionPane.YES_OPTION){
                    JFrameMaintenanceRolePegawai.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    JFrameMaintenanceRolePegawai.this.setVisible(false);
                    superAdminDashboardFrame.setEnabled(true);
                    superAdminDashboardFrame.requestFocus();
                } else {
                    JFrameMaintenanceRolePegawai.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }
            }
        });
        
        mengaturHeaderTabel();
    }
    
    public void dataKeTabel(){
        Role role = new Role();

        try{
            role.getSemuaDataRole();
            
            model.setRowCount(0);

            while (role.getResultSet().next()) {    
            Object[] fieldx = new Object[3];
                fieldx[0] = role.getResultSet().getString("Id_Role");
                fieldx[1] = role.getResultSet().getString("Nama_Role");
                fieldx[2] = role.getResultSet().getString("Tanggal_Buat");
                model.addRow(fieldx);
            }
        } catch (SQLException  e){
            e.printStackTrace();
        }
    }
    
    private void mengaturUkuranKolom(){
        TableColumn column;
        JTable_role.setAutoResizeMode(JTable_role.AUTO_RESIZE_OFF);
        column = JTable_role.getColumnModel().getColumn(0);
        column.setPreferredWidth(150);
        column = JTable_role.getColumnModel().getColumn(1);
        column.setPreferredWidth(250);
        column = JTable_role.getColumnModel().getColumn(2);
        column.setPreferredWidth(200);
    }

    
    private void mengaturHeaderTabel(){
        model = new DefaultTableModel();
        model.addColumn("Id Role");
        model.addColumn("Nama Role");
        model.addColumn("Tanggal Buat Akun");
        JTable_role.setModel(model);
        mengaturUkuranKolom();
        dataKeTabel();
    }
    
    public String generateIdRole(){
        Role role = new Role();
        String prefix = "RL";
        int counter = 1;
        String newId;

        while (true) {
            newId = prefix + String.format("%02d", counter);
            if (!role.cekIdRoleSudahAda(newId)) {
                break;
            }
            counter++;
        }

        return newId;
    }


    private void resetInputData(){
        JTextfield_idRole.setText("");
        JTextfield_namaRole.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTextfield_idRole = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_role = new javax.swing.JTable();
        JButton_saveNewRole = new javax.swing.JButton();
        JButton_close = new javax.swing.JButton();
        JButton_deleteRole = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JTextfield_namaRole = new javax.swing.JTextField();
        JButton_generateIdRole = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(84, 119, 146));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Role Pegawai");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Role");

        JTextfield_idRole.setEditable(false);
        JTextfield_idRole.setEnabled(false);

        JTable_role.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Role", "Nama Role", "Tanggal Buat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTable_role.setShowGrid(true);
        JTable_role.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_roleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable_role);

        JButton_saveNewRole.setBackground(new java.awt.Color(0, 153, 0));
        JButton_saveNewRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JButton_saveNewRole.setForeground(new java.awt.Color(255, 255, 255));
        JButton_saveNewRole.setText("Tambahkan");
        JButton_saveNewRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_saveNewRoleActionPerformed(evt);
            }
        });

        JButton_close.setBackground(new java.awt.Color(33, 52, 72));
        JButton_close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JButton_close.setForeground(new java.awt.Color(255, 255, 255));
        JButton_close.setText("Keluar");
        JButton_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_closeActionPerformed(evt);
            }
        });

        JButton_deleteRole.setBackground(new java.awt.Color(204, 0, 51));
        JButton_deleteRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JButton_deleteRole.setForeground(new java.awt.Color(255, 255, 255));
        JButton_deleteRole.setText("Hapus");
        JButton_deleteRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_deleteRoleActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Role");

        JButton_generateIdRole.setText("Generate ID");
        JButton_generateIdRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_generateIdRoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JButton_close)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JButton_saveNewRole)
                        .addGap(18, 18, 18)
                        .addComponent(JButton_deleteRole, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextfield_idRole, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JButton_generateIdRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextfield_namaRole)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButton_generateIdRole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(JTextfield_idRole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextfield_namaRole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton_saveNewRole)
                    .addComponent(JButton_deleteRole)
                    .addComponent(JButton_close))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTable_roleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_roleMouseClicked
        JTextfield_idRole.setText(model.getValueAt(JTable_role.getSelectedRow(), 0) + "");
        JTextfield_namaRole.setText(model.getValueAt(JTable_role.getSelectedRow(), 1) + "");
        JButton_saveNewRole.setText("Update");
    }//GEN-LAST:event_JTable_roleMouseClicked

    private void JButton_saveNewRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_saveNewRoleActionPerformed
        String rolename = JTextfield_namaRole.getText().trim();
        String idRole = JTextfield_idRole.getText().trim();
        Role role = new Role();
        
        if (rolename.isEmpty() || idRole.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Input masih kosong!");
            JTextfield_idRole.requestFocus();
            return;
        }
        role.getJumlahDataBerdasarkanIdRole(idRole);
        
        if (role.getAffectedRow() > 0) {
            if(JOptionPane.showConfirmDialog(this, "Role Sudah Ada! Apakah Kamu mau Update Data ini?", "info", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                role.updateRole(rolename, idRole);
                
                if (role.getAffectedRow() > 0) {
                    resetInputData();
                    dataKeTabel();
                    JButton_saveNewRole.setText("Tambahkan");
                    JOptionPane.showMessageDialog(null, "Role Berhasil Diperbarui");
                
                } else {
                    JOptionPane.showMessageDialog(null, "Role Gagal Diperbarui");
                    resetInputData();
                }
            }
        } else {
            role.memasukanRoleBaru(idRole, rolename);
            if(role.getAffectedRow()> 0) {
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                resetInputData();
                dataKeTabel();
                JOptionPane.showMessageDialog(null, "Role Berhasil Disimpan");
            
            } else {
                JOptionPane.showMessageDialog(null, "Role Gagal Disimpan");
            }
        }
    }//GEN-LAST:event_JButton_saveNewRoleActionPerformed

    private void JButton_deleteRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_deleteRoleActionPerformed
        int deleting = JOptionPane.showConfirmDialog(this, "Apakah Kamu Yakin Ingin Menghapus Data Ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        
        if(deleting == JOptionPane.YES_OPTION){
            String idRole = JTextfield_idRole.getText().trim();
            Role role = new Role();

            if(idRole.isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Role Masih Kosong!");
                JTextfield_idRole.requestFocus();
            } else {
                role.hapusRole(idRole);
                if (role.getAffectedRow() > 0) {
                    model.getDataVector().removeAllElements();
                    model.fireTableDataChanged();

                    resetInputData();

                    dataKeTabel();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                } else {
                    JOptionPane.showMessageDialog(null, "ID Tidak Ditemukan atau Tidak Dihapus");
                }
            }
        }
    }//GEN-LAST:event_JButton_deleteRoleActionPerformed

    private void JButton_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_closeActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Apakah Kamu Yakin Ingin Keluar dari Role Pegawai?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.setVisible(false);
            superAdminDashboardFrame.setEnabled(true);
            superAdminDashboardFrame.requestFocus();
        }    
    }//GEN-LAST:event_JButton_closeActionPerformed

    private void JButton_generateIdRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_generateIdRoleActionPerformed
        JTextfield_idRole.setText(generateIdRole());
    }//GEN-LAST:event_JButton_generateIdRoleActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_close;
    private javax.swing.JButton JButton_deleteRole;
    private javax.swing.JButton JButton_generateIdRole;
    private javax.swing.JButton JButton_saveNewRole;
    private javax.swing.JTable JTable_role;
    private javax.swing.JTextField JTextfield_idRole;
    private javax.swing.JTextField JTextfield_namaRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
