/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bookstore.ui.menu;

import com.bookstore.data.EmployeeAccount;
import com.bookstore.data.MysqlConnection;
import com.bookstore.data.QuerySelector;
import com.bookstore.data.SessionAccount;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rifki
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(450, 350);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        old_password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        new_password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        confirm_password = new javax.swing.JPasswordField();
        SaveNewPasswordButton = new javax.swing.JButton();
        CancelNewPasswordButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setPreferredSize(new java.awt.Dimension(430, 250));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 3, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 300));

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ganti Password");

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Masukan Password Saat Ini  ");

        old_password.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        old_password.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukan Password Baru       ");

        new_password.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Konfirmasi Password Baru    ");

        confirm_password.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N

        SaveNewPasswordButton.setBackground(new java.awt.Color(0, 153, 0));
        SaveNewPasswordButton.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        SaveNewPasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveNewPasswordButton.setText("Simpan");
        SaveNewPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveNewPasswordButtonActionPerformed(evt);
            }
        });

        CancelNewPasswordButton.setBackground(new java.awt.Color(255, 51, 0));
        CancelNewPasswordButton.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        CancelNewPasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelNewPasswordButton.setText("Batal");
        CancelNewPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelNewPasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(new_password, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(old_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(confirm_password)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CancelNewPasswordButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SaveNewPasswordButton)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(old_password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_password, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveNewPasswordButton)
                    .addComponent(CancelNewPasswordButton))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveNewPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveNewPasswordButtonActionPerformed
        EmployeeAccount employeeAccount = SessionAccount.getSessionAccount();
        String old_pwd = new String(old_password.getPassword());
        String new_pwd = new String(new_password.getPassword());
        String confirm_pwd = new String(confirm_password.getPassword());
        
        if(old_pwd.equals("") || new_pwd.equals("") && confirm_pwd.equals("")){
            JOptionPane.showMessageDialog(this, "Data Input Masih Kosong!", "Terjadi Masalah", JOptionPane.ERROR_MESSAGE);
            return;
            
        }else if(!confirm_pwd.equals(new_pwd)){
            JOptionPane.showMessageDialog(this, "Konfirmasi Password Tidak Sama!", "Terjadi Masalah", JOptionPane.ERROR_MESSAGE);
            confirm_password.setText("");
            return;
            
        } else if(old_pwd.equals(new_pwd)){
            JOptionPane.showMessageDialog(this, "Password Tidak Berubah!", "Terjadi Masalah", JOptionPane.ERROR_MESSAGE);
            new_password.setText("");
            confirm_password.setText("");
            return;
        }
        
        try {
            QuerySelector querySelector = new QuerySelector();
            ResultSet rst = querySelector.checkPassword(employeeAccount.getId(), old_pwd);

            if (rst.next()) {
                int rowsUpdated = querySelector.updatePassword(employeeAccount.getId(), confirm_pwd);
                if (rowsUpdated > 0) {
                    employeeAccount = new EmployeeAccount(
                        rst.getString("id_pegawai"),
                        rst.getString("id_role"),
                        rst.getString("nama"),
                        confirm_pwd
                    );
                    SessionAccount.setSessionAccount(employeeAccount);

                    old_password.setText("");
                    new_password.setText("");
                    confirm_password.setText("");
                    JOptionPane.showMessageDialog(this, "Password Berhasil Di Ubah!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SaveNewPasswordButtonActionPerformed

    private void CancelNewPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelNewPasswordButtonActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Apakah Kamu Yakin Ingin Keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.setVisible(false);
            this.setFocusable(false);
        }
    }//GEN-LAST:event_CancelNewPasswordButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelNewPasswordButton;
    private javax.swing.JButton SaveNewPasswordButton;
    private javax.swing.JPasswordField confirm_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField new_password;
    private javax.swing.JPasswordField old_password;
    // End of variables declaration//GEN-END:variables
}
