/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.toko_buku.ui;

import com.toko_buku.data.DbConnection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/**
 *
 * @author rifki
 */
public class RoleFrame extends javax.swing.JFrame {
    public DefaultTableModel model;
    private String idrole;
    SuperAdminFrame adminFrame;
    /**
     * Creates new form JFrameRole
     */
    public RoleFrame(SuperAdminFrame adminFrame) throws ClassNotFoundException {
        this.adminFrame = adminFrame;
        initComponents();
        HeaderTable();
        setDefaultCloseOperation(0);
        setTitle("Toko Buku - Role Pegawai");
    }
    
    public void HeaderTable() throws ClassNotFoundException{
        model = new DefaultTableModel();
        roleTable.setModel(model);
        model.addColumn("Role Id");
        model.addColumn("Role Name");
        model.addColumn("Date Create");
        columnWrapping();
        viewRole();
    }
    
    public void viewRole() throws ClassNotFoundException{
        DbConnection ctd = new DbConnection();
         
        
        try{
            Connection conn = ctd.getConnection();
            Statement statement = (Statement) conn.createStatement();
            String query = "SELECT *FROM T_Role";
//            ResultSet rst = ((java.sql.Statement) statement).executeQuery(query);
            PreparedStatement preparedStatement = conn.prepareStatement(query);
            ResultSet rs = preparedStatement.executeQuery();
            
            while (rs.next()) {
                
                Object [] fieldx = new Object[3];
                fieldx[0] = rs.getString("Id_Role");
                fieldx[1] = rs.getString("Nama_Role");
                fieldx[2] = rs.getString("Tanggal_Buat");
                
                model.addRow(fieldx);
            }
            
            
        } catch (SQLException e){
            e.printStackTrace();
        }
    }
    
    private void deleteData(){
//        this.roleid = (Integer) model.getValueAt(roleTable.getSelectedRow(), 1);
        String rolename = roleNameSearchField.getText();
        if(rolename.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Role Masih Kosong!");
            roleNameSearchField.requestFocus();
        } else{
            try {
                DbConnection ctd = new DbConnection();
                Connection conn = ctd.getConnection();
                String query = "DELETE FROM T_Role WHERE Nama_Role=?";
                PreparedStatement preparedStatement = conn.prepareStatement(query);
                preparedStatement.setString(1, rolename);
                preparedStatement.executeUpdate();
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                roleNameSearchField.setText("");
                viewRole();
                
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            } catch (ClassNotFoundException e){
                Logger.getLogger(RoleFrame.class.getName()).log(Level.SEVERE, null, e);
            } catch (SQLException ex) {
                Logger.getLogger(RoleFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        roleNameSearchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        roleTable = new javax.swing.JTable();
        SaveButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Role Pegawai");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nama Role");

        roleNameSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleNameSearchFieldActionPerformed(evt);
            }
        });

        roleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Role", "Nama Role", "Tanggal Buat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        roleTable.setShowGrid(true);
        roleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roleTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(roleTable);

        SaveButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SaveButton.setText("Tambahkan");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exitButton.setText("Keluar");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearButton.setText("Hapus");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SaveButton)
                        .addGap(18, 18, 18)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roleNameSearchField)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(roleNameSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(clearButton)
                    .addComponent(exitButton))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        int deleting = JOptionPane.showConfirmDialog(this, "Apakah Kamu Yakin Ingin Menghapus Data Ini?");
        if(deleting == JOptionPane.YES_OPTION){
            deleteData();
        } else {
            JOptionPane.showMessageDialog(null, "data Berhasil Dihapus");
        }
              
    }//GEN-LAST:event_clearButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Apakah Kamu Yakin Ingin Keluar dari Role Pegawai?") == JOptionPane.YES_OPTION){
            this.setVisible(false);
            adminFrame.setEnabled(true);
            adminFrame.requestFocus();
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        try {
            DbConnection ctd = new DbConnection();
            String rolename = roleNameSearchField.getText().trim(); 
            Date tanggal = new Date();
            SimpleDateFormat formatTanggal = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String tanggaldibuat = formatTanggal.format(tanggal);
            boolean roleExists = false;
            String datecreate = null;
            
            do {
                this.idrole = generateRandomId();
            } while (isRoleIdExists(ctd.getConnection(), idrole));

            if (rolename.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nama Role Masih Kosong!");
                roleNameSearchField.requestFocus();
            } else {
                Connection conn = ctd.getConnection();
                
                String checkQuery = "SELECT Id_Role, Tanggal_Buat FROM T_Role WHERE Nama_Role = ?";
                try (PreparedStatement checkStatement = conn.prepareStatement(checkQuery)) {
                    checkStatement.setString(1, rolename);
                    try (ResultSet rs = checkStatement.executeQuery()) {
                        if (rs.next()) {
                            roleExists = true;
                            idrole = rs.getString("Id_Role"); 
                            datecreate = rs.getString("Tanggal_Buat"); 
                        }
                    }
                }
                    String insertQuery = "INSERT INTO T_Role (Id_Role, Nama_Role, Tanggal_Buat) VALUES (?, ?, ?)";
                    try (PreparedStatement preparedStatement = conn.prepareStatement(insertQuery, Statement.RETURN_GENERATED_KEYS)) {
                        preparedStatement.setString(1, idrole);
                        preparedStatement.setString(2, rolename);
                        preparedStatement.setString(3, tanggaldibuat);

                        int dataInserted = preparedStatement.executeUpdate();

                        if (dataInserted > 0) {
                            try (ResultSet generatedKey = preparedStatement.getGeneratedKeys()) {
                                if (generatedKey.next()) {
                                    idrole = generatedKey.getString(1); 
                                }
                            }
                            model.addRow(new Object[]{idrole, rolename, tanggaldibuat, null});
                            model.getDataVector().removeAllElements();
                            model.fireTableDataChanged();
                            roleNameSearchField.setText("");
                            viewRole();
                            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                        } else {
                            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
                        }
                    } catch (SQLException sq){
                        sq.printStackTrace();
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "SQL Error: " + e.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RoleFrame.class.getName()).log(Level.SEVERE, null, ex);
        }                           
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void roleTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roleTableMouseClicked
        roleNameSearchField.setText(model.getValueAt(roleTable.getSelectedRow(), 1) + "");
//        this.roleid = (int) model.getValueAt(roleTable.getSelectedRow(), 1);
    }//GEN-LAST:event_roleTableMouseClicked

    private void roleNameSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleNameSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleNameSearchFieldActionPerformed

    private void columnWrapping(){
        TableColumn column;
        roleTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        column = roleTable.getColumnModel().getColumn(0);
        column.setPreferredWidth(150);
        column = roleTable.getColumnModel().getColumn(1);
        column.setPreferredWidth(250);
        column = roleTable.getColumnModel().getColumn(2);
        column.setPreferredWidth(200);
    }
    
    private boolean isRoleIdExists(Connection conn, String idRole) throws SQLException {
        String query = "SELECT 1 FROM T_Role WHERE Id_Role = ?";
        try (PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setString(1, idRole);
            try (ResultSet rs = stmt.executeQuery()) {
                return rs.next(); // return true jika data ditemukan
            }
        }
    }

    
    private String generateRandomId() {
        Random rand = new Random();
        int angka = 100000 + rand.nextInt(900000);
        return "RLE" + angka;
    }

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField roleNameSearchField;
    private javax.swing.JTable roleTable;
    // End of variables declaration//GEN-END:variables
}
