/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.toko_buku.ui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author rifki
 */
public class SuperAdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form CashierFrame
     */
    public SuperAdminFrame() {
        initComponents();
        setTitle("Toko Buku - Super Admin");
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e){
                int option = javax.swing.JOptionPane.showConfirmDialog(SuperAdminFrame.this, 
                        "Apakah Kamu Yakin Ingin Keluar Dari Akun?", "Konfirmasi Keluar", javax.swing.JOptionPane.YES_NO_OPTION);
                
                if(option == javax.swing.JOptionPane.YES_OPTION){
                    SuperAdminFrame.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    LoginFrame loginFrame = new LoginFrame();
                    SuperAdminFrame.this.setVisible(false);
                    loginFrame.setVisible(true);
                } else {
                    SuperAdminFrame.this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        RoleMenu = new javax.swing.JMenuItem();
        MaintenanceMenu = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();
        MasterMenu = new javax.swing.JMenu();
        MasterBukuButton = new javax.swing.JMenuItem();
        VendorMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\User\\Documents\\kuliah\\semester4\\pemrograman_desktop\\project\\toko_buku\\UAS_pemrogramanDesktop_tubes\\assets\\images\\dashboard-img-scale.jpg")); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Selamat Datang Di Halaman Utama Super Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, Short.MAX_VALUE))
        );

        FileMenu.setText("File");

        RoleMenu.setText("Role Pegawai");
        RoleMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleMenuActionPerformed(evt);
            }
        });
        FileMenu.add(RoleMenu);

        MaintenanceMenu.setText("Maintenance Pegawai");
        MaintenanceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaintenanceMenuActionPerformed(evt);
            }
        });
        FileMenu.add(MaintenanceMenu);

        exitMenu.setText("Logout");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        FileMenu.add(exitMenu);

        jMenuBar1.add(FileMenu);

        MasterMenu.setText("Data Master");

        MasterBukuButton.setText("Master Buku");
        MasterBukuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasterBukuButtonActionPerformed(evt);
            }
        });
        MasterMenu.add(MasterBukuButton);

        VendorMenu.setText("Vendor");
        VendorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendorMenuActionPerformed(evt);
            }
        });
        MasterMenu.add(VendorMenu);

        jMenuBar1.add(MasterMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaintenanceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaintenanceMenuActionPerformed
        MaintenancePegawaiFrame maintenancePegawaiFrame = new MaintenancePegawaiFrame(this);
        maintenancePegawaiFrame.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_MaintenanceMenuActionPerformed

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Apakah Kamu Yakin Ingin Keluar Dari Akun?") == JOptionPane.YES_OPTION){
            LoginFrame loginFrame = new LoginFrame();
            this.setVisible(false);
            loginFrame.setVisible(true);
        }
    }//GEN-LAST:event_exitMenuActionPerformed

    private void RoleMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleMenuActionPerformed
        try {
            RoleFrame roleFrame = new RoleFrame(this);
            roleFrame.setVisible(true);
            this.setEnabled(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SuperAdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RoleMenuActionPerformed

    private void MasterBukuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasterBukuButtonActionPerformed
        try {
            MasterBukuFrame masterBuku = new MasterBukuFrame(this);
            masterBuku.setVisible(true);
            this.setEnabled(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SuperAdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MasterBukuButtonActionPerformed

    private void VendorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendorMenuActionPerformed
        try {
            VendorFrame vendorFrame = new VendorFrame(this);
            vendorFrame.setVisible(true);
            this.setEnabled(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SuperAdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_VendorMenuActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem MaintenanceMenu;
    private javax.swing.JMenuItem MasterBukuButton;
    private javax.swing.JMenu MasterMenu;
    private javax.swing.JMenuItem RoleMenu;
    private javax.swing.JMenuItem VendorMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
