/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.toko_buku.ui;

import com.toko_buku.data.DbConnection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableColumn;

/**
 *
 * @author rifki
 */
public class VendorFrame extends javax.swing.JFrame {
    public DefaultTableModel model;
    SuperAdminFrame adminFrame;
    /**
     * Creates new form JFrameRole
     */
    public VendorFrame(SuperAdminFrame adminFrame) throws ClassNotFoundException {
        this.adminFrame = adminFrame;
        initComponents();
        HeaderTable();
        setDefaultCloseOperation(0);
        setTitle("Toko Buku - Master Buku");
    }
    
    public void HeaderTable() throws ClassNotFoundException{
        model = new DefaultTableModel();
        TabelVendor.setModel(model);
        model.addColumn("Id Vendor");
        model.addColumn("Nama Vendor");
        model.addColumn("Alamat Vendor");
        model.addColumn("Kontak Vendor");
        columnWrapping();
        viewRole();
    }
    
    private void columnWrapping(){
        TableColumn column;
        TabelVendor.setAutoResizeMode(TabelVendor.AUTO_RESIZE_OFF);
        column = TabelVendor.getColumnModel().getColumn(0);
        column.setPreferredWidth(100);
        column = TabelVendor.getColumnModel().getColumn(1);
        column.setPreferredWidth(200);
        column = TabelVendor.getColumnModel().getColumn(2);
        column.setPreferredWidth(200);
        column = TabelVendor.getColumnModel().getColumn(3);
        column.setPreferredWidth(200);
    }
    
    public void viewRole() throws ClassNotFoundException{
        DbConnection ctd = new DbConnection();
        try{
            Connection conn = ctd.getConnection();
            Statement statement = (Statement) conn.createStatement();
            String query = "SELECT *FROM T_Vendor";
            PreparedStatement preparedStatement = conn.prepareStatement(query);
            ResultSet rs = preparedStatement.executeQuery();
            
            while (rs.next()) {
                
            Object[] fieldx = new Object[4];
            fieldx[0] = rs.getString("Id_Vendor");
            fieldx[1] = rs.getString("Nama_Vendor");
            fieldx[2] = rs.getString("Alamat_Vendor");
            fieldx[3] = rs.getString("Kontak_Vendor");
                model.addRow(fieldx);
            }
        } catch (SQLException e){
            e.printStackTrace();
        }
    }
    
    private void deleteData(){
        String idVendor = FieldInputIdVendor.getText().trim();
        String namaVendor = FieldInputNamaVendor.getText().trim();
        String alamatVendor = FieldInputAlamatVendor.getText().trim();
        String kontakVendor = FieldinputKontakVendor.getText().trim();
        
        if (namaVendor.isEmpty() || idVendor.isEmpty() || alamatVendor.isEmpty() || kontakVendor.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Terdapat Data Yang Masih Kosong!");
                FieldInputIdVendor.requestFocus();
        } else {
            try {
                DbConnection ctd = new DbConnection();
                Connection conn = ctd.getConnection();
                String query = "DELETE FROM T_Vendor WHERE Id_Vendor=?";
                PreparedStatement preparedStatement = conn.prepareStatement(query);
                preparedStatement.setString(1, idVendor);
                preparedStatement.executeUpdate();
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                clearinput();
                viewRole();
                JOptionPane.showMessageDialog(null, "Vendor Berhasil Dihapus");
                
            } catch (ClassNotFoundException e){
                Logger.getLogger(VendorFrame.class.getName()).log(Level.SEVERE, null, e);
            } catch (SQLException ex) {
                Logger.getLogger(VendorFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void clearinput(){
        FieldInputIdVendor.setText("");
        FieldInputNamaVendor.setText("");
        FieldInputAlamatVendor.setText("");
        FieldinputKontakVendor.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FieldInputNamaVendor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelVendor = new javax.swing.JTable();
        TombolSimpan = new javax.swing.JButton();
        TombolKeluar = new javax.swing.JButton();
        TombolDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        FieldInputIdVendor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FieldInputAlamatVendor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FieldinputKontakVendor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List Vendor");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nama Vendor :");

        FieldInputNamaVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldInputNamaVendorActionPerformed(evt);
            }
        });

        TabelVendor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Vendor", "Nama Vendor", "Alamat Vendor", "Kontak Vendor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabelVendor.setShowGrid(true);
        TabelVendor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelVendorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelVendor);

        TombolSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TombolSimpan.setText("Tambahkan");
        TombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolSimpanActionPerformed(evt);
            }
        });

        TombolKeluar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TombolKeluar.setText("Keluar");
        TombolKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolKeluarActionPerformed(evt);
            }
        });

        TombolDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TombolDelete.setText("Hapus");
        TombolDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolDeleteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ID Vendor :");

        FieldInputIdVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldInputIdVendorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Alamat Vendor :");

        FieldInputAlamatVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldInputAlamatVendorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Kontak Vendor");

        FieldinputKontakVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldinputKontakVendorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TombolKeluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TombolSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(TombolDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldInputIdVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FieldInputAlamatVendor)
                            .addComponent(FieldinputKontakVendor)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldInputNamaVendor)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FieldInputIdVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldInputNamaVendor, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FieldInputAlamatVendor, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldinputKontakVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolSimpan)
                    .addComponent(TombolDelete)
                    .addComponent(TombolKeluar))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolDeleteActionPerformed
        int deleting = JOptionPane.showConfirmDialog(this, "Apakah Kamu Yakin Ingin Menghapus Vendor Ini?");
        if(deleting == JOptionPane.YES_OPTION){
            deleteData();
        } else {
            JOptionPane.showMessageDialog(null, "Vendor Berhasil Dihapus");
        }
              
    }//GEN-LAST:event_TombolDeleteActionPerformed

    private void TombolKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolKeluarActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Apakah Kamu Yakin Ingin Keluar dari List Vendor?") == JOptionPane.YES_OPTION){
            this.setVisible(false);
            adminFrame.setEnabled(true);
            adminFrame.requestFocus();
        }
    }//GEN-LAST:event_TombolKeluarActionPerformed

    private void TombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolSimpanActionPerformed
        try {
            DbConnection ctd = new DbConnection();

            String idVendor = FieldInputIdVendor.getText().trim();
            String namaVendor = FieldInputNamaVendor.getText().trim();
            String alamatVendor = FieldInputAlamatVendor.getText().trim();
            String kontakVendor = FieldinputKontakVendor.getText().trim();
        
        if (namaVendor.isEmpty() || idVendor.isEmpty() || alamatVendor.isEmpty() || kontakVendor.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Terdapat Data Yang Masih Kosong!");
                FieldInputIdVendor.requestFocus();
            } else {
                Connection conn = ctd.getConnection();

                // Cek apakah data dengan ISBN sudah ada
                String checkQuery = "SELECT COUNT(*) FROM T_Vendor WHERE Id_Vendor = ?";
                try (PreparedStatement checkStmt = conn.prepareStatement(checkQuery)) {
                    checkStmt.setString(1, idVendor);
                    ResultSet rs = checkStmt.executeQuery();
                    rs.next();
                    int count = rs.getInt(1);

                    if (count > 0) {
                        // UPDATE jika data sudah ada
                        String updateQuery = "UPDATE T_Vendor SET Nama_Vendor = ?, Alamat_Vendor = ?, Kontak_Vendor = ? WHERE Id_Vendor = ?";
                        try (PreparedStatement preparedStatement = conn.prepareStatement(updateQuery)) {
                            preparedStatement.setString(1, namaVendor);
                            preparedStatement.setString(2, alamatVendor);
                            preparedStatement.setString(3, kontakVendor);
                            preparedStatement.setString(4, idVendor);

                            int dataUpdated = preparedStatement.executeUpdate();

                            if (dataUpdated > 0) {
                                model.getDataVector().removeAllElements();
                                model.fireTableDataChanged();
                                clearinput();
                                viewRole(); // Pastikan fungsi ini sesuai konteksnya
                                JOptionPane.showMessageDialog(null, "Data Berhasil Diperbarui");
                            } else {
                                JOptionPane.showMessageDialog(null, "Data Gagal Diperbarui");
                            }
                        }

                    } else {
                        // INSERT jika data belum ada
                        String insertQuery = "INSERT INTO T_Vendor (Id_Vendor, Nama_Vendor, Alamat_Vendor, Kontak_Vendor) VALUES (?, ?, ?, ?)";
                        try (PreparedStatement preparedStatement = conn.prepareStatement(insertQuery)) {
                            preparedStatement.setString(1, idVendor);
                            preparedStatement.setString(2, namaVendor);
                            preparedStatement.setString(3, alamatVendor);
                            preparedStatement.setString(4, kontakVendor);


                            int dataInserted = preparedStatement.executeUpdate();

                            if (dataInserted > 0) {
                                model.getDataVector().removeAllElements();
                                model.fireTableDataChanged();
                                clearinput();
                                viewRole();
                                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                            } else {
                                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
                            }
                        }
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "SQL Error: " + e.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VendorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }                           
    }//GEN-LAST:event_TombolSimpanActionPerformed

    private void TabelVendorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelVendorMouseClicked
        FieldInputIdVendor.setText(model.getValueAt(TabelVendor.getSelectedRow(), 0) + "");
        FieldInputNamaVendor.setText(model.getValueAt(TabelVendor.getSelectedRow(), 1) + "");
        FieldInputAlamatVendor.setText(model.getValueAt(TabelVendor.getSelectedRow(), 2) + "");
        FieldinputKontakVendor.setText(model.getValueAt(TabelVendor.getSelectedRow(), 3) + "");
    }//GEN-LAST:event_TabelVendorMouseClicked

    private void FieldInputNamaVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldInputNamaVendorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldInputNamaVendorActionPerformed

    private void FieldInputAlamatVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldInputAlamatVendorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldInputAlamatVendorActionPerformed

    private void FieldinputKontakVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldinputKontakVendorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldinputKontakVendorActionPerformed

    private void FieldInputIdVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldInputIdVendorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldInputIdVendorActionPerformed


    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldInputAlamatVendor;
    private javax.swing.JTextField FieldInputIdVendor;
    private javax.swing.JTextField FieldInputNamaVendor;
    private javax.swing.JTextField FieldinputKontakVendor;
    private javax.swing.JTable TabelVendor;
    private javax.swing.JButton TombolDelete;
    private javax.swing.JButton TombolKeluar;
    private javax.swing.JButton TombolSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
