
package com.bookstore.ui.inventory_menu;
import com.bookstore.model.Rak;
import com.bookstore.ui.JFrameGudang;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.sql.*;
import javax.swing.JFrame;

/**
 *
 * @author rifki
 */
public class JFrameKonfigurasiRak extends javax.swing.JFrame {
    JFrameGudang inventoryDashboardFrame;
    private DefaultTableModel tableModel;
    /**
     * Creates new form RakConfig
     */
    public JFrameKonfigurasiRak(JFrameGudang inventoryDashboardFrame) {
        
        this.inventoryDashboardFrame = inventoryDashboardFrame;
        
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Toko Buku - Konfigurasi Rak Buku");
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int option = JOptionPane.showConfirmDialog(JFrameKonfigurasiRak.this,
                        "Apakah Kamu Yakin Ingin Keluar?",
                        "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
                if(option == JOptionPane.YES_OPTION){
                    JFrameKonfigurasiRak.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    JFrameKonfigurasiRak.this.setVisible(false);
                    inventoryDashboardFrame.setEnabled(true);
                    inventoryDashboardFrame.requestFocus();
                } else {
                    JFrameKonfigurasiRak.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }
            }
        });

        setHeaderTable();
    }
    
    private void columnSizing(){
        TableColumn column;
        JTable_rak.setAutoResizeMode(JTable_rak.AUTO_RESIZE_OFF);
        
        column = JTable_rak.getColumnModel().getColumn(0);
        column.setPreferredWidth(120);
        column = JTable_rak.getColumnModel().getColumn(1);
        column.setPreferredWidth(180);
        column = JTable_rak.getColumnModel().getColumn(2);
        column.setPreferredWidth(180);
    }
    
    private void getDataTable(){
        Rak rak = new Rak();
        
        try{
            rak.getSemuaData();
            
            tableModel.setRowCount(0);
            
            while(rak.getResultSet().next()){
                Object[] fieldx = new Object[3];
                    fieldx[0] = rak.getResultSet().getString("kode_rak");
                    fieldx[1] = rak.getResultSet().getString("nama_rak");
                    fieldx[2] = rak.getResultSet().getString("lokasi_rak");
                    this.tableModel.addRow(fieldx);
            }
            
        } catch (SQLException ex){
            ex.printStackTrace();
        }
    }
    
    private void setHeaderTable(){
        this.tableModel = new DefaultTableModel();
        JTable_rak.setModel(tableModel);
        
        tableModel.addColumn("Kode Rak");
        tableModel.addColumn("Nama Rak");
        tableModel.addColumn("Lokasi Rak");
        
        columnSizing();
        getDataTable();
    }
    
    private void clearInput(){
        JTextfield_kodeRak.setText("");
        JTextfield_namaRak.setText("");
        JTextfield_lokasiRak.setText("");
    }
    
    public String generateIdRak() {
        Rak rak = new Rak(); // Pastikan class ini memiliki method `cekIdRakSudahAda`
        String prefix = "R";
        int counter = 1;
        String newId;

        while (true) {
            newId = prefix + String.format("%02d", counter); // RK001, RK002, ...
            if (!rak.cekIdRakSudahAda(newId)) {
                break;
            }
            counter++;
        }

        return newId;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_rak = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTextfield_kodeRak = new javax.swing.JTextField();
        JTextfield_namaRak = new javax.swing.JTextField();
        JTextfield_lokasiRak = new javax.swing.JTextField();
        JButton_keluar = new javax.swing.JButton();
        JButton_mengahpusRak = new javax.swing.JButton();
        JButton_menambahkanRak = new javax.swing.JButton();
        JButton_generateIdRak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(84, 119, 146));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Konfigurasi Rak");

        JTable_rak.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        JTable_rak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Rak", "Nama Rak", "Lokasi Rak"
            }
        ));
        JTable_rak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_rakMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable_rak);

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tambah Rak");

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Kode Rak");

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Nama Rak");

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Lokasi Rak");

        JTextfield_kodeRak.setEditable(false);
        JTextfield_kodeRak.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        JTextfield_kodeRak.setEnabled(false);

        JTextfield_namaRak.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        JTextfield_lokasiRak.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        JButton_keluar.setBackground(new java.awt.Color(33, 52, 72));
        JButton_keluar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        JButton_keluar.setForeground(new java.awt.Color(255, 255, 255));
        JButton_keluar.setText("Keluar");
        JButton_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_keluarActionPerformed(evt);
            }
        });

        JButton_mengahpusRak.setBackground(new java.awt.Color(153, 0, 51));
        JButton_mengahpusRak.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        JButton_mengahpusRak.setForeground(new java.awt.Color(255, 255, 255));
        JButton_mengahpusRak.setText("Hapus");
        JButton_mengahpusRak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_mengahpusRakActionPerformed(evt);
            }
        });

        JButton_menambahkanRak.setBackground(new java.awt.Color(0, 153, 0));
        JButton_menambahkanRak.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        JButton_menambahkanRak.setForeground(new java.awt.Color(255, 255, 255));
        JButton_menambahkanRak.setText("Tambahkan Rak");
        JButton_menambahkanRak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_menambahkanRakActionPerformed(evt);
            }
        });

        JButton_generateIdRak.setText("Generate ID Rak");
        JButton_generateIdRak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_generateIdRakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTextfield_lokasiRak)
                            .addComponent(JTextfield_namaRak)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JButton_menambahkanRak)
                                .addGap(18, 18, 18)
                                .addComponent(JButton_mengahpusRak))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JTextfield_kodeRak, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JButton_generateIdRak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(JButton_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButton_generateIdRak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTextfield_kodeRak)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextfield_namaRak, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextfield_lokasiRak, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton_menambahkanRak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButton_mengahpusRak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButton_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_keluarActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Apakah Kamu Yakin Ingin Keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.setVisible(false);
            inventoryDashboardFrame.setEnabled(true);
            inventoryDashboardFrame.requestFocus();
        }
    }//GEN-LAST:event_JButton_keluarActionPerformed

    private void JButton_mengahpusRakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_mengahpusRakActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Apakah Kamu Yakin Ingin Menghapus Rak ini?", "konfirmasi hapus", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            String code = JTextfield_kodeRak.getText().trim();
            String name = JTextfield_namaRak.getText().trim();
            String location = JTextfield_lokasiRak.getText().trim();

            if (code.equals("")) {
                JOptionPane.showMessageDialog(this, "Kode rak Masih Kosong!", "Terjadi Masalah", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (name.equals("")) {
                JOptionPane.showMessageDialog(this, "Nama rak Masih Kosong!", "Terjadi Masalah", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (location.equals("")) {
                JOptionPane.showMessageDialog(this, "Lokasi rak Masih Kosong!", "Terjadi Masalah", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                Rak rak = new Rak();
                rak.getSemuaDataDariKodeRak(code);

                if (!rak.getResultSet().next()) {
                    JOptionPane.showMessageDialog(this, "Rak Tidak Ada!", "Gagal Menghapus Rak", JOptionPane.ERROR_MESSAGE);
                } else {
                    rak.updateNullKetikaRakDihapus(code);
                    rak.menghapusRak(code);

                    if (rak.getAffectedRow() > 0) {
                        tableModel.getDataVector().removeAllElements();
                        tableModel.fireTableDataChanged();

                        JTextfield_kodeRak.setText("");
                        JTextfield_namaRak.setText("");
                        JTextfield_lokasiRak.setText("");
                        getDataTable();

                        JOptionPane.showMessageDialog(this, "Rak Berhasil Dihapus", "Berhasil Menghapus Rak", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Rak Tidak Ada!", "Gagal Menghapus Rak", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_JButton_mengahpusRakActionPerformed

    private void JButton_menambahkanRakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_menambahkanRakActionPerformed
        String code = JTextfield_kodeRak.getText().trim();
        String name = JTextfield_namaRak.getText().trim();
        String location = JTextfield_lokasiRak.getText().trim();

        if(code.equals("")){
            JOptionPane.showMessageDialog(this, "Kode rak Masih Kosong!", "Terjadi Masalah", JOptionPane.ERROR_MESSAGE);
            return;
        } else if(name.equals("")){
            JOptionPane.showMessageDialog(this, "Nama rak Masih Kosong!", "Terjadi Masalah", JOptionPane.ERROR_MESSAGE);
            return;
        } else if(location.equals("")){
            JOptionPane.showMessageDialog(this, "Lokasi rak Masih Kosong!", "Terjadi Masalah", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Rak rak = new Rak();
            rak.getSemuaDataDariKodeRak(code);
            
            if(rak.getResultSet().next()){
                // Jika ada, lakukan update nama dan lokasi
                rak.memperbaruiDataRak(name, location, code);
                    JTextfield_kodeRak.setText("");
                    JTextfield_namaRak.setText("");
                    JTextfield_lokasiRak.setText("");
                    getDataTable();
                        
                JOptionPane.showMessageDialog(this, "Data Rak Berhasil Diperbarui", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Jika tidak ada, insert data baru
                rak.menambahDataRak(code, name, location);
                JTextfield_kodeRak.setText("");
                JTextfield_lokasiRak.setText("");
                JTextfield_namaRak.setText("");
                getDataTable();
                
                JOptionPane.showMessageDialog(this, "Rak Baru Berhasil Ditambahkan", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException ex){
            ex.printStackTrace();
            clearInput();
            JOptionPane.showMessageDialog(this, "Rak Sudah Ada!", "Gagal Menambahkan Rak", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JButton_menambahkanRakActionPerformed

    private void JTable_rakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_rakMouseClicked
        JTextfield_kodeRak.setText(tableModel.getValueAt(JTable_rak.getSelectedRow(), 0) + "");
        JTextfield_namaRak.setText(tableModel.getValueAt(JTable_rak.getSelectedRow(), 1) + "");
        JTextfield_lokasiRak.setText(tableModel.getValueAt(JTable_rak.getSelectedRow(), 2) + "");
    }//GEN-LAST:event_JTable_rakMouseClicked

    private void JButton_generateIdRakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_generateIdRakActionPerformed
        JTextfield_kodeRak.setText(generateIdRak());
    }//GEN-LAST:event_JButton_generateIdRakActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_generateIdRak;
    private javax.swing.JButton JButton_keluar;
    private javax.swing.JButton JButton_menambahkanRak;
    private javax.swing.JButton JButton_mengahpusRak;
    private javax.swing.JTable JTable_rak;
    private javax.swing.JTextField JTextfield_kodeRak;
    private javax.swing.JTextField JTextfield_lokasiRak;
    private javax.swing.JTextField JTextfield_namaRak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
