/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bookstore.ui.inventory_menu;

import com.bookstore.data.SesiAkunPegawai;
import com.bookstore.model.AkunPegawai;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author rifki
 */
public class JFrameGantiPassword extends javax.swing.JFrame {
    /**
     * Creates new form ChangePassword
     */
    public JFrameGantiPassword() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Toko Buku - Ganti Password");
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int option = JOptionPane.showConfirmDialog(JFrameGantiPassword.this,
                        "Apakah Kamu Yakin Ingin Keluar?",
                        "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
                if(option == JOptionPane.YES_OPTION){
                    JFrameGantiPassword.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    JFrameGantiPassword.this.setVisible(false);
                } else {
                    JFrameGantiPassword.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }
            }
        });
        
        this.setSize(450, 350);
    }
    
    private void bersihkanInputData(){
        JTextfield_oldPassword.setText("");
        JTextfield_newPassword.setText("");
        JTextfield_confirmNewPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JTextfield_oldPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        JTextfield_newPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        JTextfield_confirmNewPassword = new javax.swing.JPasswordField();
        JButton_saveNewPassword = new javax.swing.JButton();
        JButton_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jPanel1.setBackground(new java.awt.Color(84, 119, 146));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 300));

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ganti Password");

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Masukan Password Saat Ini  ");

        JTextfield_oldPassword.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        JTextfield_oldPassword.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukan Password Baru       ");

        JTextfield_newPassword.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Konfirmasi Password Baru    ");

        JTextfield_confirmNewPassword.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        JTextfield_confirmNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextfield_confirmNewPasswordActionPerformed(evt);
            }
        });

        JButton_saveNewPassword.setBackground(new java.awt.Color(33, 52, 72));
        JButton_saveNewPassword.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        JButton_saveNewPassword.setForeground(new java.awt.Color(255, 255, 255));
        JButton_saveNewPassword.setText("Simpan");
        JButton_saveNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_saveNewPasswordActionPerformed(evt);
            }
        });

        JButton_close.setBackground(new java.awt.Color(255, 51, 0));
        JButton_close.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        JButton_close.setForeground(new java.awt.Color(255, 255, 255));
        JButton_close.setText("Batal");
        JButton_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JTextfield_newPassword)
                                    .addComponent(JTextfield_oldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(JTextfield_confirmNewPassword)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JButton_close)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JButton_saveNewPassword)))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextfield_oldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextfield_newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTextfield_confirmNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton_saveNewPassword)
                    .addComponent(JButton_close))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_saveNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_saveNewPasswordActionPerformed
        String passwordLama = new String(JTextfield_oldPassword.getPassword());
        String passwordBaru = new String(JTextfield_newPassword.getPassword());
        String konfirmasiPassword = new String(JTextfield_confirmNewPassword.getPassword());
        
        if (passwordLama.equals("")){
            JOptionPane.showMessageDialog(null, "password lama masih kosong!", "error", JOptionPane.ERROR_MESSAGE);
            bersihkanInputData();
        } else if (passwordBaru.equals("")){
            JOptionPane.showMessageDialog(null, "password baru masih kosong!", "error", JOptionPane.ERROR_MESSAGE);
            bersihkanInputData();
        } else if (konfirmasiPassword.equals("")){
            JOptionPane.showMessageDialog(null, "konfirmasi password baru masih kosong!", "error", JOptionPane.ERROR_MESSAGE);
            bersihkanInputData();
        } else {
            AkunPegawai akunPegawai = SesiAkunPegawai.getSesiAkunPegawai();
            
            akunPegawai.gantiPassword(passwordLama, passwordBaru, konfirmasiPassword);
            bersihkanInputData();
        }
        
    }//GEN-LAST:event_JButton_saveNewPasswordActionPerformed

    private void JButton_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_closeActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Apakah Kamu Yakin Ingin Keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.setVisible(false);
            this.setFocusable(false);
        }
    }//GEN-LAST:event_JButton_closeActionPerformed

    private void JTextfield_confirmNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextfield_confirmNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextfield_confirmNewPasswordActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_close;
    private javax.swing.JButton JButton_saveNewPassword;
    private javax.swing.JPasswordField JTextfield_confirmNewPassword;
    private javax.swing.JPasswordField JTextfield_newPassword;
    private javax.swing.JPasswordField JTextfield_oldPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
