
package com.bookstore.ui.inventory_menu;
import com.bookstore.data.QuerySelector;
import com.bookstore.ui.InventoryDashboardFrame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.sql.*;
import javax.swing.JFrame;

/**
 *
 * @author rifki
 */
public class RackConfig extends javax.swing.JFrame {
    InventoryDashboardFrame inventoryDashboardFrame;
    private DefaultTableModel tableModel;
    QuerySelector querySelector;
    /**
     * Creates new form RakConfig
     */
    public RackConfig(InventoryDashboardFrame inventoryDashboardFrame) {
        
        this.inventoryDashboardFrame = inventoryDashboardFrame;
        
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Toko Buku - Konfigurasi Rak Buku");
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int option = JOptionPane.showConfirmDialog(
                        RackConfig.this,
                        "Apakah Kamu Yakin Ingin Keluar?",
                        "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
                if(option == JOptionPane.YES_OPTION){
                    RackConfig.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    RackConfig.this.setVisible(false);
                    inventoryDashboardFrame.setEnabled(true);
                    inventoryDashboardFrame.requestFocus();
                } else {
                    RackConfig.this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }
            }
        });

        setHeaderTable();
    }
    
    private void columnSizing(){
        TableColumn column;
        RackTable.setAutoResizeMode(RackTable.AUTO_RESIZE_OFF);
        
        column = RackTable.getColumnModel().getColumn(0);
        column.setPreferredWidth(120);
        column = RackTable.getColumnModel().getColumn(1);
        column.setPreferredWidth(180);
        column = RackTable.getColumnModel().getColumn(2);
        column.setPreferredWidth(180);
    }
    
    private void getDataTable(){
        this.querySelector = new QuerySelector();
        
        try{
            querySelector.selectAllFromTable("T_Rak");
            
            while(querySelector.getResultSet().next()){
                Object[] fieldx = new Object[3];
                    fieldx[0] = querySelector.getResultSet().getString("kode_rak");
                    fieldx[1] = querySelector.getResultSet().getString("nama_rak");
                    fieldx[2] = querySelector.getResultSet().getString("lokasi_rak");
                    this.tableModel.addRow(fieldx);
            }
            
        } catch (SQLException | ClassNotFoundException ex){
            ex.printStackTrace();
        }
    }
    
    private void setHeaderTable(){
        this.tableModel = new DefaultTableModel();
        RackTable.setModel(tableModel);
        
        tableModel.addColumn("Kode Rak");
        tableModel.addColumn("Nama Rak");
        tableModel.addColumn("Lokasi Rak");
        
        columnSizing();
        getDataTable();
    }
    
    private void clearInput(){
        rack_code.setText("");
        rack_name.setText("");
        rack_location.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RackTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rack_code = new javax.swing.JTextField();
        rack_name = new javax.swing.JTextField();
        rack_location = new javax.swing.JTextField();
        CloseButton = new javax.swing.JButton();
        DeleteSelectedRackButton = new javax.swing.JButton();
        AddNewRackButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(84, 119, 146));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 3, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Konfigurasi Rak");

        RackTable.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        RackTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Rak", "Nama Rak", "Lokasi Rak"
            }
        ));
        RackTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RackTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(RackTable);

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tambah Rak");

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Kode Rak");

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Nama Rak");

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Lokasi Rak");

        rack_code.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        rack_name.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        rack_location.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        CloseButton.setBackground(new java.awt.Color(33, 52, 72));
        CloseButton.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        CloseButton.setForeground(new java.awt.Color(255, 255, 255));
        CloseButton.setText("Keluar");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        DeleteSelectedRackButton.setBackground(new java.awt.Color(153, 0, 51));
        DeleteSelectedRackButton.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        DeleteSelectedRackButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteSelectedRackButton.setText("Hapus");
        DeleteSelectedRackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSelectedRackButtonActionPerformed(evt);
            }
        });

        AddNewRackButton1.setBackground(new java.awt.Color(0, 153, 0));
        AddNewRackButton1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        AddNewRackButton1.setForeground(new java.awt.Color(255, 255, 255));
        AddNewRackButton1.setText("Tambahkan Rak");
        AddNewRackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewRackButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rack_location, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                            .addComponent(rack_name)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(AddNewRackButton1)
                                .addGap(18, 18, 18)
                                .addComponent(DeleteSelectedRackButton))
                            .addComponent(rack_code)))
                    .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rack_code))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rack_name)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rack_location)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNewRackButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteSelectedRackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Apakah Kamu Yakin Ingin Keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.setVisible(false);
            inventoryDashboardFrame.setEnabled(true);
            inventoryDashboardFrame.requestFocus();
        }
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void DeleteSelectedRackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSelectedRackButtonActionPerformed
        String code = rack_code.getText().trim();
        String name = rack_name.getText().trim();
        String location = rack_location.getText().trim();

        if (code.equals("")) {
            JOptionPane.showMessageDialog(this, "Kode rak Masih Kosong!", "Terjadi Masalah", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (name.equals("")) {
            JOptionPane.showMessageDialog(this, "Nama rak Masih Kosong!", "Terjadi Masalah", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (location.equals("")) {
            JOptionPane.showMessageDialog(this, "Lokasi rak Masih Kosong!", "Terjadi Masalah", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Cek apakah rak ada
            querySelector.countDataByColumn("T_Rak", "Kode_rak", code);

            if (querySelector.getAffectedRows() <= 0) {
                JOptionPane.showMessageDialog(this, "Rak Tidak Ada!", "Gagal Menghapus Rak", JOptionPane.ERROR_MESSAGE);
            } else {
                // SET NULL ke foreign key di tabel buku (atau tabel lain jika ada)
                querySelector.setColumnToNullByCondition("T_DetailMasterbuku", "kode_rak", "kode_rak", code); // implementasi dinamis

                // Hapus rak
                querySelector.deleteByKey("T_Rak", "Kode_rak", code);

                if (querySelector.getAffectedRows() > 0) {
                    tableModel.getDataVector().removeAllElements();
                    tableModel.fireTableDataChanged();

                    rack_code.setText("");
                    rack_name.setText("");
                    rack_location.setText("");
                    getDataTable();

                    JOptionPane.showMessageDialog(this, "Rak Berhasil Dihapus", "Berhasil Menghapus Rak", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Rak Tidak Ada!", "Gagal Menghapus Rak", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_DeleteSelectedRackButtonActionPerformed

    private void AddNewRackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewRackButton1ActionPerformed
        String code = rack_code.getText().trim();
        String name = rack_name.getText().trim();
        String location = rack_location.getText().trim();

        if(code.equals("")){
            JOptionPane.showMessageDialog(this, "Kode rak Masih Kosong!", "Terjadi Masalah", JOptionPane.ERROR_MESSAGE);
            return;
        } else if(name.equals("")){
            JOptionPane.showMessageDialog(this, "Nama rak Masih Kosong!", "Terjadi Masalah", JOptionPane.ERROR_MESSAGE);
            return;
        } else if(location.equals("")){
            JOptionPane.showMessageDialog(this, "Lokasi rak Masih Kosong!", "Terjadi Masalah", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Cek apakah data dengan kode_rak sudah ada
            querySelector.countDataByColumn("T_Rak", "kode_rak", code);

            if(querySelector.getAffectedRows() > 0){
                // Jika ada, lakukan update nama dan lokasi
                querySelector.updateTwoColumns("T_Rak", "nama_rak", name, "lokasi_rak", location, "kode_rak", code);
                JOptionPane.showMessageDialog(this, "Data Rak Berhasil Diperbarui", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Jika tidak ada, insert data baru
                querySelector.insertThreeColumns("T_Rak", "kode_rak", "nama_rak", "lokasi_rak", code, name, location);
                JOptionPane.showMessageDialog(this, "Rak Baru Berhasil Ditambahkan", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException | ClassNotFoundException ex){
            ex.printStackTrace();
            clearInput();
            JOptionPane.showMessageDialog(this, "Rak Sudah Ada!", "Gagal Menambahkan Rak", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddNewRackButton1ActionPerformed

    private void RackTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RackTableMouseClicked
        rack_code.setText(tableModel.getValueAt(RackTable.getSelectedRow(), 0) + "");
        rack_name.setText(tableModel.getValueAt(RackTable.getSelectedRow(), 1) + "");
        rack_location.setText(tableModel.getValueAt(RackTable.getSelectedRow(), 2) + "");
    }//GEN-LAST:event_RackTableMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewRackButton1;
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton DeleteSelectedRackButton;
    private javax.swing.JTable RackTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField rack_code;
    private javax.swing.JTextField rack_location;
    private javax.swing.JTextField rack_name;
    // End of variables declaration//GEN-END:variables
}
